// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : flowers1
Date           : Tue Jun 30 15:25:44 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/flowers1/May2015/CMSSW_7_2_3/src/ttH-LeptonPlusJets/AnalysisCode/macros/TRAINHOUSE
Training events: 1696
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
second_jet_pt                 second_jet_pt                 second_jet_pt                 second_jet_pt                 second_jet_pt                     'F'    [36.6424789429,732.424926758]
third_jet_pt                  third_jet_pt                  third_jet_pt                  third_jet_pt                  third_jet_pt                      'F'    [32.2821540833,352.907562256]
fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                     'F'    [30.6958827972,248.460678101]
all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met               'F'    [267.039550781,2131.44018555]
HT                            HT                            HT                            HT                            HT                                'F'    [186.953201294,1724.15161133]
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [0.638118386269,3.8753182888]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.829765856266,0.999360322952]
dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags           'F'    [2.95704154496e-07,0.00757151795551]
h3                            h3                            h3                            h3                            h3                                'F'    [-0.0246332604438,0.990658700466]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.817660033703,0.999751091003]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.814050495625,0.998661339283]
maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                    'F'    [0.0701468288898,1.62478983402]
maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                    'F'    [0.0473143011332,1.51063418388]
maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                    'F'    [0.00447914982215,1.53125190735]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "second_jet_pt", "third_jet_pt", "fourth_jet_pt", "all_sum_pt_with_met", "HT", "avg_dr_tagged_jets", "avg_btag_disc_btags", "dev_from_avg_disc_btags", "h3", "second_highest_btag", "third_highest_btag", "maxeta_jet_jet", "maxeta_jet_tag", "maxeta_tag_tag" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356105,-0.0287791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544286,0.00885714) , 
3, 533.383, 1, 0, 0.451009,-0.0489914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804545,0.0609091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511364,0.00227273) , 
5, 2.32714, 1, 0, 0.720779,0.220779) , 
6, 0.975133, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320513,-0.0330477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52972,0.00505876) , 
3, 533.383, 1, 0, 0.427549,-0.067691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702355,0.0381591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378378,-0.0238667) , 
5, 2.46738, 1, 0, 0.640138,0.130941) , 
6, 0.958981, 1, 0, 0.5,3.31786e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329167,-0.0307735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515419,0.00365617) , 
2, 44.7239, 1, 0, 0.451009,-0.0411316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804545,0.0515371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511364,0.00217917) , 
5, 2.32714, 1, 0, 0.720779,0.185377) , 
6, 0.975133, 1, 0, 0.5,3.10144e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352155,-0.0244723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553892,0.00941645) , 
3, 622.163, 1, 0, 0.419067,-0.0657961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693458,0.032378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0253048) , 
5, 2.46505, 1, 0, 0.618287,0.096204) , 
10, 0.90196, 1, 0, 0.5,1.64489e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0562061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57971,0.0137225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393235,-0.0178225) , 
5, 2.35621, 1, 0, 0.523779,0.020966) , 
4, 260.153, 1, 0, 0.5,1.91155e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150943,-0.0561028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475819,-0.002923) , 
4, 259.07, 1, 0, 0.451009,-0.0343295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792929,0.0452627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.00776431) , 
11, 0.851844, 1, 0, 0.720779,0.154743) , 
6, 0.975133, 1, 0, 0.5,6.81691e-06)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196078,-0.0491133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441358,-0.00963506) , 
1, 54.9074, 1, 0, 0.362683,-0.109669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474922,-0.00316269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640275,0.0217011) , 
3, 549.868, 1, 0, 0.553733,0.0429259) , 
6, 0.926677, 1, 0, 0.5,8.64726e-06)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537143,0.0106509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398609,-0.0162134) , 
8, 0.217103, 1, 0, 0.451009,-0.0299299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804545,0.0397693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511364,0.000463925) , 
5, 2.32714, 1, 0, 0.720779,0.134869) , 
6, 0.975133, 1, 0, 0.5,-1.79067e-06)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225,-0.0398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462094,-0.00515412) , 
3, 498.368, 1, 0, 0.362683,-0.0956869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599051,0.0153324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452128,-0.00949203) , 
8, 0.410492, 1, 0, 0.553733,0.0374684) , 
6, 0.926677, 1, 0, 0.5,1.84854e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268817,-0.0336932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56701,0.00929328) , 
9, 0.982621, 1, 0, 0.345745,-0.109379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585821,0.0126399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362903,-0.0205755) , 
5, 2.48605, 1, 0, 0.543939,0.031161) , 
2, 41.0656, 1, 0, 0.5,3.58375e-06)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579882,0.0182364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364048,-0.0195241) , 
8, 0.126218, 1, 0, 0.407942,-0.0572381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632061,0.0188942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452381,-0.0126706) , 
12, 0.813815, 1, 0, 0.588439,0.0549696) , 
3, 533.383, 1, 0, 0.5,-9.5246e-06)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369792,-0.0164026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577406,0.0127169) , 
2, 65.3474, 1, 0, 0.419067,-0.0459837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693458,0.023822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0193586) , 
5, 2.46505, 1, 0, 0.618287,0.0671838) , 
10, 0.90196, 1, 0, 0.5,-9.40126e-06)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0422779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610561,0.0163837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469619,-0.00532683) , 
8, 0.217103, 1, 0, 0.523779,0.014611) , 
4, 260.153, 1, 0, 0.5,-2.04009e-06)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369792,-0.0147278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577406,0.0112991) , 
2, 65.3474, 1, 0, 0.419067,-0.0411038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693458,0.0214332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0171542) , 
5, 2.46505, 1, 0, 0.618287,0.0600422) , 
10, 0.90196, 1, 0, 0.5,-1.32096e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0385879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592697,0.0141077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467052,-0.0066864) , 
11, 0.736422, 1, 0, 0.523779,0.0129485) , 
4, 260.153, 1, 0, 0.5,-6.00229e-06)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196078,-0.0359927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441358,-0.00669227) , 
1, 54.9074, 1, 0, 0.362683,-0.0746102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504141,0.00121857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743083,0.0259318) , 
6, 0.978622, 1, 0, 0.553733,0.0291719) , 
6, 0.926677, 1, 0, 0.5,-1.68066e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552294,0.00724754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754717,0.0365062) , 
1, 101.48, 1, 0, 0.585253,0.0573855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00575254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35124,-0.0228311) , 
11, 0.780781, 1, 0, 0.44689,-0.0357799) , 
8, 0.217103, 1, 0, 0.5,-1.88853e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503937,0.00482064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326667,-0.0212746) , 
8, 0.254799, 1, 0, 0.407942,-0.0435674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632061,0.0147394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452381,-0.0100297) , 
12, 0.813815, 1, 0, 0.588439,0.0418236) , 
3, 533.383, 1, 0, 0.5,-1.60012e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429658,-0.00393304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280374,-0.0269083) , 
11, 0.845234, 1, 0, 0.362683,-0.0669752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504141,0.00111697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743083,0.0236368) , 
6, 0.978622, 1, 0, 0.553733,0.0261827) , 
6, 0.926677, 1, 0, 0.5,-1.79977e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293103,-0.0246951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523256,0.00952617) , 
0, 102.907, 1, 0, 0.345745,-0.0758021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600215,0.0105522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410714,-0.00955955) , 
5, 2.3439, 1, 0, 0.543939,0.021574) , 
2, 41.0656, 1, 0, 0.5,-1.41016e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495845,0.001314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696552,0.0217607) , 
9, 0.973732, 1, 0, 0.585253,0.0481827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00493946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35124,-0.0195505) , 
11, 0.780781, 1, 0, 0.44689,-0.030048) , 
8, 0.217103, 1, 0, 0.5,-1.96307e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28483,-0.0208846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508516,0.000196134) , 
6, 0.926677, 1, 0, 0.445415,-0.026265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694444,0.0216434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497797,-0.0026726) , 
5, 2.24863, 1, 0, 0.61343,0.0545291) , 
3, 622.163, 1, 0, 0.5,-1.64548e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0321745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443601,-0.00423237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636641,0.011476) , 
10, 0.90196, 1, 0, 0.523779,0.0100203) , 
4, 260.153, 1, 0, 0.5,-1.59183e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552294,0.00526551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754717,0.0297686) , 
1, 101.48, 1, 0, 0.585253,0.0429693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00441652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35124,-0.0176003) , 
11, 0.780781, 1, 0, 0.44689,-0.0268032) , 
8, 0.217103, 1, 0, 0.5,-2.14054e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268817,-0.0220078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56701,0.00843038) , 
9, 0.982621, 1, 0, 0.345745,-0.0623422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585821,0.007432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362903,-0.0119668) , 
5, 2.48605, 1, 0, 0.543939,0.0177344) , 
2, 41.0656, 1, 0, 0.5,-1.84012e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488943,0.000820722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338369,-0.0187308) , 
8, 0.415203, 1, 0, 0.445415,-0.0222951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734848,0.0293883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575179,0.00371329) , 
13, 0.312625, 1, 0, 0.61343,0.0462521) , 
3, 622.163, 1, 0, 0.5,-2.53344e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586957,0.0127541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417266,-0.00720758) , 
8, 0.120408, 1, 0, 0.451009,-0.0150531) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.823077,0.0328766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646067,0.00386411) , 
13, 0.439407, 1, 0, 0.720779,0.0677198) , 
6, 0.975133, 1, 0, 0.5,-2.12634e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0284148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387471,-0.00934548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575044,0.00604915) , 
6, 0.926677, 1, 0, 0.523779,0.00847542) , 
4, 260.153, 1, 0, 0.5,-7.09689e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579882,0.013806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364048,-0.0117661) , 
8, 0.126218, 1, 0, 0.407942,-0.0293673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663866,0.0155415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535433,-0.000570666) , 
13, 0.4407, 1, 0, 0.588439,0.0281829) , 
3, 533.383, 1, 0, 0.5,-1.53088e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369792,-0.00914085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577406,0.00797719) , 
2, 65.3474, 1, 0, 0.419067,-0.0229997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693458,0.0136114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0125703) , 
5, 2.46505, 1, 0, 0.618287,0.0335824) , 
10, 0.90196, 1, 0, 0.5,-1.32322e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0255524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592697,0.00852222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467052,-0.00409226) , 
11, 0.736422, 1, 0, 0.523779,0.0073635) , 
4, 260.153, 1, 0, 0.5,-8.91638e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559792,0.00624584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4164,-0.0070603) , 
8, 0.217103, 1, 0, 0.470976,-0.00909512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774194,0.0276036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712644,0.00845253) , 
6, 0.990942, 1, 0, 0.744444,0.0764703) , 
6, 0.983208, 1, 0, 0.5,-1.38898e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55642,0.00574387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41488,-0.00889583) , 
11, 0.781809, 1, 0, 0.484655,-0.00759219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681818,0.0194269) , 
4, 699.353, 1, 0, 0.5,-7.64558e-06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50505,0.00696186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325397,-0.0132589) , 
8, 0.123898, 1, 0, 0.362683,-0.040018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599051,0.00751836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452128,-0.00567662) , 
8, 0.410492, 1, 0, 0.553733,0.0156515) , 
6, 0.926677, 1, 0, 0.5,-5.51592e-06)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280992,-0.0304356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376471,-0.00116557) , 
5, 2.09124, 1, 0, 0.345745,-0.045536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563473,0.00451954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30303,-0.0184195) , 
5, 2.77034, 1, 0, 0.543939,0.0129615) , 
2, 41.0656, 1, 0, 0.5,-7.25886e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488943,0.000762344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338369,-0.0146088) , 
8, 0.415203, 1, 0, 0.445415,-0.0164338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734848,0.0239745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575179,0.00233707) , 
13, 0.312625, 1, 0, 0.61343,0.0341115) , 
3, 622.163, 1, 0, 0.5,-1.25248e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573407,0.000612666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608392,0.0271199) , 
7, 0.00136997, 1, 0, 0.579191,0.0231784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448494,-0.00149912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32,-0.017285) , 
8, 0.458839, 1, 0, 0.417569,-0.0241467) , 
7, 0.00180297, 1, 0, 0.5,-9.75685e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586957,0.00931254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417266,-0.00530692) , 
8, 0.120408, 1, 0, 0.451009,-0.0108585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792929,0.0218503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,-0.00451973) , 
11, 0.851844, 1, 0, 0.720779,0.0488661) , 
6, 0.975133, 1, 0, 0.5,-1.22773e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55642,0.00514434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41488,-0.00787922) , 
11, 0.781809, 1, 0, 0.484655,-0.00653831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681818,0.0169995) , 
4, 699.353, 1, 0, 0.5,-2.52713e-06)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0221067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457965,-0.00328862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612184,0.00751544) , 
3, 584.07, 1, 0, 0.523779,0.00608814) , 
4, 260.153, 1, 0, 0.5,-1.1229e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429658,-0.000885128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280374,-0.016668) , 
11, 0.845234, 1, 0, 0.362683,-0.0342978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504141,0.000356204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743083,0.0144741) , 
6, 0.978622, 1, 0, 0.553733,0.0134138) , 
6, 0.926677, 1, 0, 0.5,-5.10352e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537736,0.000979251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629214,0.030277) , 
8, 0.325296, 1, 0, 0.545542,0.0157285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343891,-0.0135654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601896,0.010558) , 
2, 61.8051, 1, 0, 0.427259,-0.0251334) , 
8, 0.362145, 1, 0, 0.5,-4.30729e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.020079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387471,-0.0064655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575044,0.00408584) , 
6, 0.926677, 1, 0, 0.523779,0.00538588) , 
4, 260.153, 1, 0, 0.5,-7.09192e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696629,0.0211689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577197,0.00359058) , 
8, 0.0488383, 1, 0, 0.598039,0.0296714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349745,-0.00998384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564489,0.0037332) , 
3, 535.211, 1, 0, 0.457841,-0.012775) , 
8, 0.168756, 1, 0, 0.5,-1.10781e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605263,0.00659803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427451,-0.00407783) , 
7, 0.00180297, 1, 0, 0.518234,0.00553238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0150375) , 
5, 2.79625, 1, 0, 0.5,-1.05048e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.0134216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482205,-0.000446792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711864,0.0215239) , 
4, 699.353, 1, 0, 0.499678,0.00549886) , 
5, 1.56303, 1, 0, 0.5,-1.06014e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316239,-0.0107683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517597,0.00117437) , 
2, 41.0656, 1, 0, 0.470976,-0.00622535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774194,0.0221778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712644,0.00392736) , 
6, 0.990942, 1, 0, 0.744444,0.0523771) , 
6, 0.983208, 1, 0, 0.5,-5.75076e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632184,0.0174892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431336,-0.00403489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620229,0.00573105) , 
9, 0.982409, 1, 0, 0.492853,-0.00410029) , 
13, 0.149886, 1, 0, 0.5,-3.91125e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577488,0.000507122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528796,0.0154201) , 
12, 0.890247, 1, 0, 0.56592,0.0183636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527054,0.0040881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330789,-0.0139881) , 
11, 0.779353, 1, 0, 0.440583,-0.0165567) , 
8, 0.26545, 1, 0, 0.5,-2.52045e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.0124191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516506,0.0024992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247423,-0.0203583) , 
5, 2.88544, 1, 0, 0.499678,0.00508236) , 
5, 1.56303, 1, 0, 0.5,-6.77493e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.017504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635294,0.0129817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510306,-0.00045376) , 
11, 0.4403, 1, 0, 0.523779,0.00452272) , 
4, 260.153, 1, 0, 0.5,-8.52329e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696629,0.019136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577197,0.00280054) , 
8, 0.0488383, 1, 0, 0.598039,0.0249037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578313,0.00919968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425827,-0.0055109) , 
13, 0.295293, 1, 0, 0.457841,-0.0107234) , 
8, 0.168756, 1, 0, 0.5,-1.00481e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381766,-0.00105912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0189) , 
6, 0.917397, 1, 0, 0.362683,-0.0250151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568311,0.00386383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460606,-0.0082777) , 
11, 1.10658, 1, 0, 0.553733,0.00977816) , 
6, 0.926677, 1, 0, 0.5,-7.45104e-06)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.0115623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482205,-0.000419007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711864,0.0191857) , 
4, 699.353, 1, 0, 0.499678,0.00471905) , 
5, 1.56303, 1, 0, 0.5,-8.4211e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559792,0.00403416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4164,-0.0044518) , 
8, 0.217103, 1, 0, 0.470976,-0.00529639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774194,0.0200721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712644,0.0026349) , 
6, 0.990942, 1, 0, 0.744444,0.0445649) , 
6, 0.983208, 1, 0, 0.5,-4.50355e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632184,0.0152444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431336,-0.00337832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620229,0.00471492) , 
9, 0.982409, 1, 0, 0.492853,-0.00353767) , 
13, 0.149886, 1, 0, 0.5,-1.37149e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0159211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457965,-0.00260747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612184,0.00559845) , 
3, 584.07, 1, 0, 0.523779,0.00402524) , 
4, 260.153, 1, 0, 0.5,-4.27477e-07)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478587,-0.00037502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778261,0.0147556) , 
6, 0.975011, 1, 0, 0.537801,0.00969486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488,0.00208611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248408,-0.0223169) , 
12, 0.781652, 1, 0, 0.417293,-0.0212198) , 
8, 0.410492, 1, 0, 0.5,-2.42453e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.010791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482205,-0.000308468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711864,0.0170789) , 
4, 699.353, 1, 0, 0.499678,0.00438606) , 
5, 1.56303, 1, 0, 0.5,-3.13439e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515705,-3.45989e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505882,0.0227928) , 
12, 1.00496, 1, 0, 0.515131,0.00572007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433824,-0.0136062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377358,-0.00013508) , 
12, 1.12151, 1, 0, 0.409091,-0.0343695) , 
11, 1.10658, 1, 0, 0.5,-2.64838e-07)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605263,0.00518708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427451,-0.00328476) , 
7, 0.00180297, 1, 0, 0.518234,0.00403024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0113579) , 
5, 2.79625, 1, 0, 0.5,-2.08181e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632184,0.0138248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539315,0.00195345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418152,-0.00502946) , 
8, 0.362145, 1, 0, 0.492853,-0.00318255) , 
13, 0.149886, 1, 0, 0.5,-2.53488e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0145709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677419,0.0156694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514151,-0.000100698) , 
11, 0.366269, 1, 0, 0.523779,0.00361211) , 
4, 260.153, 1, 0, 0.5,-2.13026e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.00986885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516506,0.00199952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247423,-0.0167062) , 
5, 2.88544, 1, 0, 0.499678,0.0040023) , 
5, 1.56303, 1, 0, 0.5,-3.12475e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515705,-5.71199e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505882,0.020696) , 
12, 1.00496, 1, 0, 0.515131,0.00510416) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433824,-0.0124752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377358,0.000256918) , 
12, 1.12151, 1, 0, 0.409091,-0.0306997) , 
11, 1.10658, 1, 0, 0.5,-4.64512e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445578,-0.00733296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655647,0.0123447) , 
2, 51.4354, 1, 0, 0.561644,0.0159471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405405,-0.0270672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467672,0.000724282) , 
13, 0.49291, 1, 0, 0.46102,-0.0100931) , 
13, 0.4407, 1, 0, 0.5,-5.59972e-06)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696629,0.0167171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577197,0.00181871) , 
8, 0.0488383, 1, 0, 0.598039,0.0191155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349745,-0.00735183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564489,0.00309806) , 
3, 535.211, 1, 0, 0.457841,-0.00822295) , 
8, 0.168756, 1, 0, 0.5,-2.08401e-06)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381766,-0.000369356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0169114) , 
6, 0.917397, 1, 0, 0.362683,-0.0201097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573913,-0.00163379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52741,0.00613605) , 
13, 0.570904, 1, 0, 0.553733,0.00786635) , 
6, 0.926677, 1, 0, 0.5,-1.91724e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632184,0.0128109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452614,-0.00239195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620779,0.00466222) , 
2, 65.766, 1, 0, 0.492853,-0.00292319) , 
13, 0.149886, 1, 0, 0.5,-3.3765e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314815,-0.0108045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,0.0184418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516915,-0.000581493) , 
9, 0.894981, 1, 0, 0.512594,0.00311166) , 
9, 0.869686, 1, 0, 0.5,-2.30544e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.00901553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482205,-0.000278952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711864,0.0146754) , 
4, 699.353, 1, 0, 0.499678,0.00364306) , 
5, 1.56303, 1, 0, 0.5,-4.64339e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445578,-0.00610283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655647,0.0110757) , 
2, 51.4354, 1, 0, 0.561644,0.0150623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405405,-0.0240636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467672,0.000496788) , 
13, 0.49291, 1, 0, 0.46102,-0.00952813) , 
13, 0.4407, 1, 0, 0.5,-2.25171e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555172,-0.00299651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520548,0.00654175) , 
12, 0.628186, 1, 0, 0.537801,0.008089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488,0.00225064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248408,-0.0202477) , 
12, 0.781652, 1, 0, 0.417293,-0.0176983) , 
8, 0.410492, 1, 0, 0.5,7.05828e-08)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421245,0.00149362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284314,-0.012938) , 
5, 2.26711, 1, 0, 0.362683,-0.0191689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573913,-0.00134462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52741,0.00558944) , 
13, 0.570904, 1, 0, 0.553733,0.00749455) , 
6, 0.926677, 1, 0, 0.5,-4.54577e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515705,3.42598e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505882,0.0180766) , 
12, 1.00496, 1, 0, 0.515131,0.00480843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491803,-0.000558738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325,-0.0132518) , 
8, 0.25206, 1, 0, 0.409091,-0.0289347) , 
11, 1.10658, 1, 0, 0.5,-6.33885e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445578,-0.0052086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655647,0.0102979) , 
2, 51.4354, 1, 0, 0.561644,0.0148299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405405,-0.0214911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467672,0.000218316) , 
13, 0.49291, 1, 0, 0.46102,-0.0093899) , 
13, 0.4407, 1, 0, 0.5,-7.5957e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60066,0.00559854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438582,-0.00256948) , 
8, 0.120408, 1, 0, 0.470976,-0.00400785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774194,0.0171891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712644,0.000593153) , 
6, 0.990942, 1, 0, 0.744444,0.0337059) , 
6, 0.983208, 1, 0, 0.5,-5.21207e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632184,0.0118717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431336,-0.0025646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620229,0.00355779) , 
9, 0.982409, 1, 0, 0.492853,-0.00268403) , 
13, 0.149886, 1, 0, 0.5,-2.31552e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531532,0.0179458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570325,8.763e-05) , 
6, 0.912742, 1, 0, 0.564644,0.0122309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423168,-0.00444012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0170462) , 
3, 833.721, 1, 0, 0.447761,-0.00988661) , 
11, 0.736422, 1, 0, 0.5,-1.54128e-06)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573407,-0.0021575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608392,0.0245285) , 
7, 0.00136997, 1, 0, 0.579191,0.0108668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425373,0.0022092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40339,-0.0108917) , 
10, 0.861832, 1, 0, 0.417569,-0.011314) , 
7, 0.00180297, 1, 0, 0.5,-1.24869e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15625,-0.022207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414698,-0.0010852) , 
3, 421.259, 1, 0, 0.362683,-0.0186819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506812,0.00671933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573944,-0.000621648) , 
9, 0.964757, 1, 0, 0.553733,0.00730818) , 
6, 0.926677, 1, 0, 0.5,-1.51811e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.00846583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516506,0.00173341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247423,-0.014826) , 
5, 2.88544, 1, 0, 0.499678,0.00340319) , 
5, 1.56303, 1, 0, 0.5,-5.89585e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60066,0.00512049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438582,-0.0023497) , 
8, 0.120408, 1, 0, 0.470976,-0.0036517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774194,0.0158862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712644,0.00051951) , 
6, 0.990942, 1, 0, 0.744444,0.0306913) , 
6, 0.983208, 1, 0, 0.5,-6.79975e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378505,0.00332748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34981,-0.00974184) , 
9, 0.893256, 1, 0, 0.362683,-0.0165544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645161,0.00836942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530381,-0.000193778) , 
13, 0.300117, 1, 0, 0.553733,0.00647212) , 
6, 0.926677, 1, 0, 0.5,-4.07366e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314815,-0.00951977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,0.0170532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516915,-0.000583421) , 
9, 0.894981, 1, 0, 0.512594,0.00269729) , 
9, 0.869686, 1, 0, 0.5,-4.0781e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.00793396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516506,0.00158885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247423,-0.0134465) , 
5, 2.88544, 1, 0, 0.499678,0.00318498) , 
5, 1.56303, 1, 0, 0.5,-5.69643e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515705,-3.39024e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505882,0.0168205) , 
12, 1.00496, 1, 0, 0.515131,0.00419587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433824,-0.010941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377358,0.000920135) , 
12, 1.12151, 1, 0, 0.409091,-0.0252546) , 
11, 1.10658, 1, 0, 0.5,-6.37978e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184874,-0.0119068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592697,0.00411497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467052,-0.00219256) , 
11, 0.736422, 1, 0, 0.523779,0.00282865) , 
4, 260.153, 1, 0, 0.5,-6.53279e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296443,-0.00710659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515152,0.0129051) , 
4, 291.392, 1, 0, 0.408124,0.0160089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419178,-0.00967861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594595,0.00202114) , 
3, 544.11, 1, 0, 0.540288,-0.00703019) , 
4, 333.353, 1, 0, 0.5,-7.06227e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632184,0.0104371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507042,-0.00198577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438066,0.00512681) , 
13, 0.80777, 1, 0, 0.492853,-0.0023387) , 
13, 0.149886, 1, 0, 0.5,-8.56554e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381766,-6.67709e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0141085) , 
6, 0.917397, 1, 0, 0.362683,-0.0155925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506812,0.00615811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573944,-0.00076649) , 
9, 0.964757, 1, 0, 0.553733,0.00609081) , 
6, 0.926677, 1, 0, 0.5,-7.62192e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392405,-0.00973868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61523,0.00695553) , 
9, 0.931178, 1, 0, 0.561644,0.0122812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451064,-0.0137352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46393,0.0017325) , 
13, 0.544827, 1, 0, 0.46102,-0.00777929) , 
13, 0.4407, 1, 0, 0.5,-8.20434e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539185,-0.000642864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531401,0.0113616) , 
8, 0.326089, 1, 0, 0.537801,0.00659231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488,0.00227175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248408,-0.0179984) , 
12, 0.781652, 1, 0, 0.417293,-0.0144451) , 
8, 0.410492, 1, 0, 0.5,-6.69988e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.00714529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52071,-0.00385559) , 
11, 0.935164, 1, 0, 0.598039,0.0146159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349745,-0.00559668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564489,0.00226666) , 
3, 535.211, 1, 0, 0.457841,-0.00629944) , 
8, 0.168756, 1, 0, 0.5,-1.00539e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296443,-0.0063468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515152,0.0118074) , 
4, 291.392, 1, 0, 0.408124,0.0149748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654472,0.00835442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510182,-0.00394865) , 
13, 0.295293, 1, 0, 0.540288,-0.00657963) , 
4, 333.353, 1, 0, 0.5,-9.08582e-06)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503448,-0.00756155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482205,-0.00020109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711864,0.0120522) , 
4, 699.353, 1, 0, 0.499678,0.00301812) , 
5, 1.56303, 1, 0, 0.5,-8.43068e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60066,0.00475146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438582,-0.00213481) , 
8, 0.120408, 1, 0, 0.470976,-0.00319205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774194,0.0144062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712644,0.000229744) , 
6, 0.990942, 1, 0, 0.744444,0.0268252) , 
6, 0.983208, 1, 0, 0.5,-6.25402e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234783,-0.0148526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457711,0.00776508) , 
0, 55.0933, 1, 0, 0.408124,0.0138056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419178,-0.00830043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594595,0.00170622) , 
3, 544.11, 1, 0, 0.540288,-0.0060595) , 
4, 333.353, 1, 0, 0.5,-3.92937e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410898,-0.005475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621145,0.00322002) , 
3, 547.071, 1, 0, 0.516176,-0.00453824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427928,0.013008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447368,-0.0106172) , 
4, 426.954, 1, 0, 0.434524,0.0183362) , 
13, 0.804217, 1, 0, 0.5,-6.51156e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515705,-6.13935e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505882,0.0156314) , 
12, 1.00496, 1, 0, 0.515131,0.00377461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433824,-0.00979023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377358,0.000640235) , 
12, 1.12151, 1, 0, 0.409091,-0.0227345) , 
11, 1.10658, 1, 0, 0.5,-7.94256e-06)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
