// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : gsmith
Date           : Sat May 18 15:20:13 2013
Host           : Linux lxbuild167.cern.ch 2.6.18-308.1.1.el5 #1 SMP Wed Mar 7 19:25:07 CET 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/gsmith/cms_work/CMSSW_5_2_6/src/AnalysisCode/LeptonPlusJets/macros/tmva
Training events: 823
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "823" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
first_jet_pt                  first_jet_pt                  first_jet_pt                  first_jet_pt                  first_jet_pt                      'F'    [41.0718307495,615.717346191]
second_jet_pt                 second_jet_pt                 second_jet_pt                 second_jet_pt                 second_jet_pt                     'F'    [35.1325492859,373.155578613]
fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                     'F'    [30.0028038025,128.079940796]
all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met               'F'    [233.263809204,1409.2310791]
HT                            HT                            HT                            HT                            HT                                'F'    [149.638656616,1107.56396484]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.760934233665,0.995705485344]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.727201044559,0.999999403954]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.697790265083,0.999981462955]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [0.679353833199,0.985076129436]
M3                            M3                            M3                            M3                            M3                                'F'    [74.7271270752,952.208984375]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "first_jet_pt", "second_jet_pt", "fourth_jet_pt", "all_sum_pt_with_met", "HT", "avg_btag_disc_btags", "second_highest_btag", "third_highest_btag", "fourth_highest_btag", "M3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 41.0718307495117;
      fVmax[0] = 615.717346191406;
      fVmin[1] = 35.1325492858887;
      fVmax[1] = 373.155578613281;
      fVmin[2] = 30.0028038024902;
      fVmax[2] = 128.079940795898;
      fVmin[3] = 233.263809204102;
      fVmax[3] = 1409.23107910156;
      fVmin[4] = 149.638656616211;
      fVmax[4] = 1107.56396484375;
      fVmin[5] = 0.760934233665466;
      fVmax[5] = 0.995705485343933;
      fVmin[6] = 0.727201044559479;
      fVmax[6] = 0.999999403953552;
      fVmin[7] = 0.697790265083313;
      fVmax[7] = 0.999981462955475;
      fVmin[8] = 0.679353833198547;
      fVmax[8] = 0.985076129436493;
      fVmin[9] = 74.7271270751953;
      fVmax[9] = 952.208984375;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704969,0.0409938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518692,0.00373832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25784,-0.0484321) , 
3, 467.294, 0, 0, 0.369261,-0.130739) , 
7, 0.913641, 0, 0, 0.500608,0.000607533)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0660819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560897,0.0111295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307692,-0.0360081) , 
3, 457.258, 0, 0, 0.424556,-0.0710656) , 
5, 0.950987, 0, 0, 0.500608,0.000544673)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728571,0.0397669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524229,0.00298354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281646,-0.037083) , 
3, 467.294, 0, 0, 0.383057,-0.101049) , 
5, 0.928628, 0, 0, 0.500608,0.000504323)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0566935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514943,0.00327292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261411,-0.0398398) , 
3, 401.259, 0, 0, 0.424556,-0.0597799) , 
5, 0.950987, 0, 0, 0.500608,0.00045294)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704969,0.0309462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469055,-0.00466609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21134,-0.0435974) , 
3, 411.886, 0, 0, 0.369261,-0.0966687) , 
7, 0.913641, 0, 0, 0.500608,0.000431534)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613027,0.0177578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566038,0.0112941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0395273) , 
3, 619.74, 0, 0, 0.305648,-0.149352) , 
5, 0.895089, 0, 0, 0.500608,0.000373349)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756757,0.0364246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520505,0.0062087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.0348186) , 
9, 206.077, 0, 0, 0.40599,-0.0640783) , 
8, 0.868611, 0, 0, 0.500608,0.000313131)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0459296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532394,0.00698034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305296,-0.0277313) , 
9, 206.077, 0, 0, 0.424556,-0.0457578) , 
5, 0.950987, 0, 0, 0.500608,0.000288304)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613027,0.0149535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595238,0.0151847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258687,-0.0325347) , 
3, 673.1, 0, 0, 0.305648,-0.123584) , 
5, 0.895089, 0, 0, 0.500608,0.000291273)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.0135524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404372,-0.0159922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14433,-0.0481632) , 
8, 0.766088, 0, 0, 0.314286,-0.126206) , 
3, 401.259, 0, 0, 0.500608,0.000239841)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664,0.0199315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472103,-0.00187199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246512,-0.0324638) , 
9, 206.077, 0, 0, 0.363839,-0.07809) , 
8, 0.824936, 0, 0, 0.500608,0.000183404)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0396133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59447,0.0126256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344227,-0.017815) , 
3, 513.256, 0, 0, 0.424556,-0.0374666) , 
5, 0.950987, 0, 0, 0.500608,0.00015067)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.0116362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373418,-0.0121061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237705,-0.0382697) , 
1, 59.8334, 0, 0, 0.314286,-0.106988) , 
3, 401.259, 0, 0, 0.500608,0.00016961)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561747,0.00802862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290598,-0.0251065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119048,-0.0580564) , 
6, 0.921986, 1, 0, 0.245283,-0.156207) , 
5, 0.87273, 0, 0, 0.500608,0.000136242)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704969,0.0198469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54902,0.00630161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29023,-0.0210872) , 
4, 381.651, 0, 0, 0.369261,-0.0580517) , 
7, 0.913641, 0, 0, 0.500608,9.81035e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64133,0.0145739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.00169098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229167,-0.0303443) , 
9, 206.077, 0, 0, 0.353234,-0.0695888) , 
8, 0.810378, 0, 0, 0.500608,8.4993e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.0101754) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373418,-0.0102773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237705,-0.0348344) , 
1, 59.8334, 0, 0, 0.314286,-0.0923786) , 
3, 401.259, 0, 0, 0.500608,5.83225e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576355,0.0082538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45283,0.00532071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229814,-0.033633) , 
5, 0.880687, 0, 0, 0.285047,-0.107604) , 
7, 0.856081, 0, 0, 0.500608,3.71529e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0328717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716981,0.0332812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399679,-0.00967663) , 
2, 72.0359, 0, 0, 0.424556,-0.028933) , 
5, 0.950987, 0, 0, 0.500608,1.27351e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0180922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544681,0.00885794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314103,-0.023456) , 
2, 40.4496, 0, 0, 0.413163,-0.0422549) , 
3, 513.256, 0, 0, 0.500608,4.65744e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613027,0.00937945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595238,0.00946896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258687,-0.0212988) , 
3, 673.1, 0, 0, 0.305648,-0.073703) , 
5, 0.895089, 0, 0, 0.500608,3.60806e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00845389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373418,-0.00789294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237705,-0.0305822) , 
1, 59.8334, 0, 0, 0.314286,-0.0753289) , 
3, 401.259, 0, 0, 0.500608,1.85534e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756757,0.0208075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520505,0.00304819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278169,-0.0193358) , 
9, 206.077, 0, 0, 0.40599,-0.0324361) , 
8, 0.868611, 0, 0, 0.500608,3.5021e-06)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561747,0.00558694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25641,-0.0149182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,-0.0469943) , 
2, 52.6996, 1, 0, 0.245283,-0.104407) , 
5, 0.87273, 0, 0, 0.500608,4.67417e-06)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0153514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544681,0.00799063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314103,-0.0204689) , 
2, 40.4496, 0, 0, 0.413163,-0.0351357) , 
3, 513.256, 0, 0, 0.500608,-6.22159e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0517691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592697,0.00902022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372315,-0.0130359) , 
2, 44.0138, 0, 0, 0.473548,-0.0120475) , 
8, 0.926843, 0, 0, 0.500608,-1.07912e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576355,0.00630506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45283,0.0060791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229814,-0.0271748) , 
5, 0.880687, 0, 0, 0.285047,-0.0790828) , 
7, 0.856081, 0, 0, 0.500608,1.53429e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0258626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716981,0.0265808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399679,-0.00731068) , 
2, 72.0359, 0, 0, 0.424556,-0.0206677) , 
5, 0.950987, 0, 0, 0.500608,-1.99518e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598291,0.00848349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480687,-0.001988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163934,-0.0325641) , 
8, 0.766088, 0, 0, 0.371831,-0.0496489) , 
9, 200.082, 0, 0, 0.500608,2.23889e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704969,0.0122298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369412,-0.00302636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368421,-0.0297759) , 
9, 330.432, 1, 0, 0.369261,-0.032766) , 
7, 0.913641, 0, 0, 0.500608,-1.46966e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0132568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43,-0.0027197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234043,-0.0485605) , 
9, 301.537, 1, 0, 0.413163,-0.0295647) , 
3, 513.256, 0, 0, 0.500608,5.66766e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00647573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345455,-0.0378559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306667,-0.00753148) , 
6, 0.987008, 0, 0, 0.314286,-0.0556248) , 
3, 401.259, 0, 0, 0.500608,4.10441e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0469045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57631,0.0059903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339286,-0.0137832) , 
9, 200.082, 0, 0, 0.473548,-0.00976849) , 
8, 0.926843, 0, 0, 0.500608,3.05229e-06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576355,0.00529166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320755,-0.0266061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.00149583) , 
1, 85.6659, 0, 0, 0.285047,-0.0646836) , 
7, 0.856081, 0, 0, 0.500608,2.10746e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780822,0.0281562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482912,0.000812082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38961,-0.0310579) , 
9, 340.027, 1, 0, 0.473333,-0.0113457) , 
2, 72.0359, 0, 0, 0.500608,1.53602e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628261,0.00744193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.00849625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293286,-0.0147956) , 
8, 0.81887, 0, 0, 0.338843,-0.0398411) , 
7, 0.884861, 0, 0, 0.500608,2.41958e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598291,0.00714755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37247,-0.00170515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37037,-0.0273867) , 
1, 84.1762, 1, 0, 0.371831,-0.0408817) , 
9, 200.082, 0, 0, 0.500608,1.59364e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00586276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345455,-0.0348201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306667,-0.00658571) , 
6, 0.987008, 0, 0, 0.314286,-0.0495302) , 
3, 401.259, 0, 0, 0.500608,1.35974e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0439261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592697,0.00724581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372315,-0.0101179) , 
2, 44.0138, 0, 0, 0.473548,-0.00849148) , 
8, 0.926843, 0, 0, 0.500608,1.11903e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524812,0.00570578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.0199406) , 
9, 325.436, 1, 0, 0.52129,0.00827323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0342054) , 
7, 0.784131, 0, 0, 0.500608,2.84431e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0108555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43,-0.0018899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234043,-0.0427798) , 
9, 301.537, 1, 0, 0.413163,-0.0234782) , 
3, 513.256, 0, 0, 0.500608,1.95987e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598291,0.00634137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491228,0.0202165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348993,-0.014393) , 
9, 134.159, 1, 0, 0.371831,-0.0358336) , 
9, 200.082, 0, 0, 0.500608,1.43121e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0199365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445151,-0.00124395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148936,-0.0356796) , 
7, 0.783491, 0, 0, 0.424556,-0.0144242) , 
5, 0.950987, 0, 0, 0.500608,7.19826e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00500512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345455,-0.0320651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306667,-0.0050285) , 
6, 0.987008, 0, 0, 0.314286,-0.0416404) , 
3, 401.259, 0, 0, 0.500608,9.16456e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628261,0.00636586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390863,-0.0153251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277108,0.00306536) , 
1, 83.4456, 0, 0, 0.338843,-0.0333362) , 
7, 0.884861, 0, 0, 0.500608,7.09355e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780822,0.0242839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482912,0.000776454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38961,-0.026643) , 
9, 340.027, 1, 0, 0.473333,-0.00927717) , 
2, 72.0359, 0, 0, 0.500608,5.94124e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.00957238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43,-0.00160107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234043,-0.0385458) , 
9, 301.537, 1, 0, 0.413163,-0.0203457) , 
3, 513.256, 0, 0, 0.500608,1.21858e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598291,0.00579652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37247,0.000184064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37037,-0.0254352) , 
1, 84.1762, 1, 0, 0.371831,-0.0322705) , 
9, 200.082, 0, 0, 0.500608,6.95734e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0401942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592697,0.00613044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372315,-0.00853964) , 
2, 44.0138, 0, 0, 0.473548,-0.00702716) , 
8, 0.926843, 0, 0, 0.500608,4.70061e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64133,0.00654212) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364407,-0.00173923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270833,-0.0406971) , 
8, 0.797088, 1, 0, 0.353234,-0.027633) , 
8, 0.810378, 0, 0, 0.500608,1.91793e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00453862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345455,-0.0295155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306667,-0.00437956) , 
6, 0.987008, 0, 0, 0.314286,-0.0371612) , 
3, 401.259, 0, 0, 0.500608,1.51233e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561747,0.00310218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25641,-0.00158162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,-0.0410628) , 
2, 52.6996, 1, 0, 0.245283,-0.0538487) , 
5, 0.87273, 0, 0, 0.500608,1.23004e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780822,0.0213368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482912,0.000810807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38961,-0.0240438) , 
9, 340.027, 1, 0, 0.473333,-0.00783292) , 
2, 72.0359, 0, 0, 0.500608,3.87891e-06)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524862,0.00360652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.0272494) , 
9, 409.006, 1, 0, 0.52129,0.00617107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0275977) , 
7, 0.784131, 0, 0, 0.500608,8.42147e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.0086589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544681,0.00683534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314103,-0.0134451) , 
2, 40.4496, 0, 0, 0.413163,-0.0180762) , 
3, 513.256, 0, 0, 0.500608,3.85653e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.037479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57631,0.00424016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339286,-0.00942136) , 
9, 200.082, 0, 0, 0.473548,-0.00608011) , 
8, 0.926843, 0, 0, 0.500608,-2.56524e-07)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628261,0.00506532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390863,-0.0137503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277108,0.00488512) , 
1, 83.4456, 0, 0, 0.338843,-0.0258171) , 
7, 0.884861, 0, 0, 0.500608,1.09658e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00406515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345455,-0.0270745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306667,-0.00371764) , 
6, 0.987008, 0, 0, 0.314286,-0.0328174) , 
3, 401.259, 0, 0, 0.500608,8.52255e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0156705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465753,-0.0130862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413208,0.000644003) , 
9, 288.98, 0, 0, 0.424556,-0.010437) , 
5, 0.950987, 0, 0, 0.500608,6.35159e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.00788861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43,-0.00108906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234043,-0.034275) , 
9, 301.537, 1, 0, 0.413163,-0.0162551) , 
3, 513.256, 0, 0, 0.500608,1.40296e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598291,0.00474468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376307,-0.000429002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352941,-0.0309097) , 
0, 132.409, 1, 0, 0.371831,-0.0256838) , 
9, 200.082, 0, 0, 0.500608,8.32801e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524862,0.00328575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.0252606) , 
9, 409.006, 1, 0, 0.52129,0.00537624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0249525) , 
7, 0.784131, 0, 0, 0.500608,5.70844e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780822,0.0194205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490909,0.0222106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471942,-0.00355071) , 
9, 133.683, 1, 0, 0.473333,-0.00689643) , 
2, 72.0359, 0, 0, 0.500608,1.87547e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00384175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373418,0.000600924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237705,-0.0198864) , 
1, 59.8334, 0, 0, 0.314286,-0.0307321) , 
3, 401.259, 0, 0, 0.500608,3.69008e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557003,-0.00662307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661458,0.0263487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351852,-0.00990915) , 
9, 193.821, 0, 0, 0.467054,0.0160062) , 
9, 241.867, 0, 0, 0.500608,-3.17539e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71875,0.0139422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495614,5.30877e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0930233,-0.0405082) , 
7, 0.784131, 0, 0, 0.471802,-0.00752925) , 
3, 681.251, 0, 0, 0.500608,2.56036e-07)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0343571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,0.0190992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446479,-0.00296791) , 
2, 72.0359, 0, 0, 0.473548,-0.00510139) , 
8, 0.926843, 0, 0, 0.500608,-1.05396e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557003,-0.00631242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661458,0.0240189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351852,-0.00874675) , 
9, 193.821, 0, 0, 0.467054,0.015188) , 
9, 241.867, 0, 0, 0.500608,5.05689e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64133,0.00483606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364407,-0.00012581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270833,-0.0378543) , 
8, 0.797088, 1, 0, 0.353234,-0.0196676) , 
8, 0.810378, 0, 0, 0.500608,7.95793e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.00680249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463768,0.0216577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405858,-0.00702871) , 
9, 142.77, 1, 0, 0.413163,-0.0137554) , 
3, 513.256, 0, 0, 0.500608,4.08558e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00323056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319588,-0.000415555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.0203598) , 
3, 369.232, 1, 0, 0.314286,-0.0255276) , 
3, 401.259, 0, 0, 0.500608,7.08213e-07)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541667,-0.00833701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631922,0.0133141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351852,-0.0079684) , 
9, 193.918, 0, 0, 0.488114,0.0102986) , 
9, 283.651, 0, 0, 0.500608,-2.15865e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557003,-0.00591602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661458,0.0209934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351852,-0.00719605) , 
9, 193.821, 0, 0, 0.467054,0.0141729) , 
9, 241.867, 0, 0, 0.500608,-5.7106e-08)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0323561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688525,0.0105461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433384,-0.00339828) , 
3, 625.253, 0, 0, 0.473548,-0.00452354) , 
8, 0.926843, 0, 0, 0.500608,3.4404e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628261,0.00410002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390863,-0.0131904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277108,0.00728392) , 
1, 83.4456, 0, 0, 0.338843,-0.0201995) , 
7, 0.884861, 0, 0, 0.500608,1.38676e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536653,0.00160907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245614,0.00655944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232558,-0.0321471) , 
2, 43.6669, 1, 0, 0.24,-0.0461078) , 
7, 0.812911, 0, 0, 0.500608,1.00673e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71875,0.0119828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495614,9.08091e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0930233,-0.0369997) , 
7, 0.784131, 0, 0, 0.471802,-0.00631041) , 
3, 681.251, 0, 0, 0.500608,3.44825e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557003,-0.00542912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661458,0.0192395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351852,-0.00656242) , 
9, 193.821, 0, 0, 0.467054,0.0129154) , 
9, 241.867, 0, 0, 0.500608,-6.16751e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.00603461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447689,-0.00847578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308824,0.0154839) , 
6, 0.922056, 0, 0, 0.413163,-0.0120136) , 
3, 513.256, 0, 0, 0.500608,-2.39615e-06)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539763,-0.00271537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522523,0.0253102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289256,-0.0106691) , 
0, 80.038, 0, 0, 0.400862,0.0273199) , 
0, 95.8, 0, 0, 0.500608,-7.60599e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85034,0.0125184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461378,-0.00506029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335025,0.00663477) , 
0, 95.8, 0, 0, 0.424556,-0.00783184) , 
5, 0.950987, 0, 0, 0.500608,-1.29934e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00315092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345455,-0.0244976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306667,-0.00189633) , 
6, 0.987008, 0, 0, 0.314286,-0.0245631) , 
3, 401.259, 0, 0, 0.500608,-8.46668e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780822,0.0152188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490909,0.0234206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471942,-0.00323077) , 
9, 133.683, 1, 0, 0.473333,-0.00511347) , 
2, 72.0359, 0, 0, 0.500608,-8.75727e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.00288859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319588,0.000205213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.0193469) , 
3, 369.232, 1, 0, 0.314286,-0.0224819) , 
3, 401.259, 0, 0, 0.500608,-7.78531e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64133,0.00407594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364407,0.000422068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270833,-0.0355173) , 
8, 0.797088, 1, 0, 0.353234,-0.0162657) , 
8, 0.810378, 0, 0, 0.500608,-9.55236e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557003,-0.00507233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661458,0.0177073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351852,-0.00594957) , 
9, 193.821, 0, 0, 0.467054,0.0120032) , 
9, 241.867, 0, 0, 0.500608,-1.1982e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69697,0.0127139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701493,0.0179763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462319,-0.00311127) , 
1, 143.69, 0, 0, 0.483487,-0.00465292) , 
0, 232.62, 0, 0, 0.500608,-7.95349e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539763,-0.00249645) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628571,0.0310181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302469,-0.00479944) , 
4, 251.509, 0, 0, 0.400862,0.0249142) , 
0, 95.8, 0, 0, 0.500608,-3.95995e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0298593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,0.0159569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446479,-0.00237678) , 
2, 72.0359, 0, 0, 0.473548,-0.00389189) , 
8, 0.926843, 0, 0, 0.500608,-4.01026e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541667,-0.00698703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591647,0.00812109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265,-0.0113866) , 
8, 0.766776, 0, 0, 0.488114,0.00851863) , 
9, 283.651, 0, 0, 0.500608,6.47388e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69697,0.0119859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543986,0.00232721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315,-0.0110177) , 
2, 34.6731, 0, 0, 0.483487,-0.00434548) , 
0, 232.62, 0, 0, 0.500608,3.67812e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504202,-0.0088009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,0.00478116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.0241869) , 
7, 0.816627, 0, 0, 0.5,0.005961) , 
9, 325.436, 0, 0, 0.500608,1.96041e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.00523446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447689,-0.00793419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308824,0.0152671) , 
6, 0.922056, 0, 0, 0.413163,-0.010246) , 
3, 513.256, 0, 0, 0.500608,-5.94251e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539763,-0.00233231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522523,0.0215884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289256,-0.00930332) , 
0, 80.038, 0, 0, 0.400862,0.0230797) , 
0, 95.8, 0, 0, 0.500608,-1.0754e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596685,0.0025732) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352941,0.0115741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301887,-0.0108723) , 
9, 147.018, 1, 0, 0.314286,-0.0198073) , 
3, 401.259, 0, 0, 0.500608,-1.36833e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628261,0.00333096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390863,-0.0117631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277108,0.00747231) , 
1, 83.4456, 0, 0, 0.338843,-0.0161021) , 
7, 0.884861, 0, 0, 0.500608,-1.6188e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673913,0.00511765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463768,0.0204197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405858,-0.00591153) , 
9, 142.77, 1, 0, 0.413163,-0.00999836) , 
3, 513.256, 0, 0, 0.500608,-1.70332e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541667,-0.00629084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671171,0.0127946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388753,-0.0039098) , 
3, 468.578, 0, 0, 0.488114,0.00760012) , 
9, 283.651, 0, 0, 0.500608,-1.8141e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9375,0.0276716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606498,0.00489378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399598,-0.00411682) , 
2, 48.6842, 0, 0, 0.473548,-0.00341874) , 
8, 0.926843, 0, 0, 0.500608,-1.35401e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539763,-0.00224488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653061,0.0345471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.00181396) , 
1, 73.122, 0, 0, 0.400862,0.0220885) , 
0, 95.8, 0, 0, 0.500608,-5.99768e-06)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
