import FWCore.ParameterSet.Config as cms

SelectedJetProducer = cms.EDProducer(
    "SelectedJetProducer",
    isData=cms.bool(False),
    applyCorrection=cms.bool(True),
    doDeltaRCleaning=cms.bool(True),
    isSubjetCollection=cms.bool(False),
    jets=cms.InputTag("slimmedJets"),
    electrons=cms.InputTag("SelectedElectronProducer:selectedElectronsLoose"),
    muons=cms.InputTag("SelectedMuonProducer:selectedMuonsLoose"),
    photons=cms.InputTag("SelectedPhotonProducer:selectedPhotonsLoose"),
    rho=cms.InputTag("fixedGridRhoFastjetAll"),
    ptMins=cms.vdouble(30, 20),
    etaMaxs=cms.vdouble(2.4, 2.4),
    PUJetIDMins=cms.vstring("none", "none"),
    leptonJetDr=cms.double(0.4),
    collectionNames=cms.vstring("selectedJets", "selectedJetsLoose"),
    systematics=cms.vstring(""),
    JetID=cms.vstring("none"),
    JetType=cms.string("AK4PFCHS"),
    jecFileAK4_2016=cms.string("Summer16_07Aug2017_V11_MC_UncertaintySources_AK4PFPuppi.txt"),
    jecFileAK8_2016=cms.string("Summer16_07Aug2017_V11_MC_UncertaintySources_AK8PFPuppi.txt"),
    jecFileAK15_2016=cms.string("Summer16_07Aug2017_V11_MC_UncertaintySources_AK8PFPuppi.txt"),
    jecFileAK4_2017=cms.string("Fall17_17Nov2017_V32_MC_UncertaintySources_AK4PFPuppi.txt"),
    jecFileAK8_2017=cms.string("Fall17_17Nov2017_V32_MC_UncertaintySources_AK8PFPuppi.txt"),
    jecFileAK15_2017=cms.string("Fall17_17Nov2017_V32_MC_UncertaintySources_AK8PFPuppi.txt"),
    jecFileAK4_2018=cms.string("Autumn18_V19_MC_UncertaintySources_AK4PFPuppi.txt"),
    jecFileAK8_2018=cms.string("Autumn18_V19_MC_UncertaintySources_AK8PFPuppi.txt"),
    jecFileAK15_2018=cms.string("Autumn18_V19_MC_UncertaintySources_AK8PFPuppi.txt"),
    era=cms.string("2017"),
)
