// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : flowers1
Date           : Tue Jun 30 15:26:16 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/flowers1/May2015/CMSSW_7_2_3/src/ttH-LeptonPlusJets/AnalysisCode/macros/TRAINHOUSE
Training events: 3558
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
third_jet_pt                  third_jet_pt                  third_jet_pt                  third_jet_pt                  third_jet_pt                      'F'    [35.6347389221,404.997650146]
fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                     'F'    [31.0393600464,272.157501221]
all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met               'F'    [319.916503906,2725.078125]
HT                            HT                            HT                            HT                            HT                                'F'    [237.168273926,2316.91772461]
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [0.649570405483,4.03804826736]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.831326246262,0.999477803707]
dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags           'F'    [5.74442040602e-08,0.00755156995729]
h3                            h3                            h3                            h3                            h3                                'F'    [-0.00363862630911,0.978437840939]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.81786519289,0.999973535538]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.814031362534,0.999041140079]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [0.0824545547366,0.813898563385]
maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                    'F'    [0.0344956256449,1.78096556664]
maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                    'F'    [0.00236317515373,1.52456736565]
min_dr_tagged_jets            min_dr_tagged_jets            min_dr_tagged_jets            min_dr_tagged_jets            min_dr_tagged_jets                'F'    [0.289608567953,3.40344047546]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.267095595598,0.976083517075]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "third_jet_pt", "fourth_jet_pt", "all_sum_pt_with_met", "HT", "avg_dr_tagged_jets", "avg_btag_disc_btags", "dev_from_avg_disc_btags", "h3", "second_highest_btag", "third_highest_btag", "fourth_highest_btag", "maxeta_jet_tag", "maxeta_tag_tag", "min_dr_tagged_jets", "pt_all_jets_over_E_all_jets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371479,-0.0257042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507278,0.0014556) , 
14, 0.575516, 1, 0, 0.445817,-0.0541833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556876,0.0113752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723312,0.0446623) , 
10, 0.500312, 1, 0, 0.629771,0.129771) , 
9, 0.919751, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370572,-0.0247122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504613,0.00193009) , 
3, 534.275, 1, 0, 0.445817,-0.0487662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556876,0.0102391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723312,0.0402793) , 
10, 0.500312, 1, 0, 0.629771,0.116801) , 
9, 0.919751, 1, 0, 0.5,1.05408e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345253,-0.0273377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488389,-0.0011641) , 
14, 0.542149, 1, 0, 0.435359,-0.0542276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633535,0.0234197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438679,-0.0155008) , 
4, 2.55458, 1, 0, 0.60336,0.0867224) , 
9, 0.902131, 1, 0, 0.5,5.22791e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367442,-0.0225256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506598,0.0025145) , 
3, 534.275, 1, 0, 0.445264,-0.0424724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504155,-0.002061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674142,0.0284972) , 
10, 0.326204, 1, 0, 0.619303,0.0925888) , 
5, 0.959442, 1, 0, 0.5,4.67184e-06)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368373,-0.0223927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524532,0.00321252) , 
5, 0.943427, 1, 0, 0.447404,-0.0470306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505682,0.00111648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676056,0.0315869) , 
14, 0.610488, 1, 0, 0.586746,0.0775855) , 
10, 0.535253, 1, 0, 0.5,6.91377e-06)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463912,-0.00545476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611564,0.0187369) , 
10, 0.535253, 1, 0, 0.519926,0.0183734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299065,-0.0372394) , 
4, 2.7472, 1, 0, 0.5,6.89378e-06)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423146,-0.0112024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614094,0.0234873) , 
3, 930.418, 1, 0, 0.445817,-0.0352128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594293,0.010112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747934,0.0403343) , 
9, 0.976407, 1, 0, 0.629771,0.084356) , 
9, 0.919751, 1, 0, 0.5,5.90399e-06)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321569,-0.0335369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536888,0.00648448) , 
1, 42.5212, 1, 0, 0.519926,0.0165213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299065,-0.0336533) , 
4, 2.7472, 1, 0, 0.5,1.06246e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462283,-0.00492745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615966,0.0180554) , 
10, 0.535253, 1, 0, 0.520305,0.0183892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425414,-0.0133263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275556,-0.0413342) , 
7, 0.31213, 1, 0, 0.342365,-0.142728) , 
12, 0.94468, 1, 0, 0.5,4.33695e-06)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327517,-0.0251248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492843,0.00110368) , 
3, 534.275, 1, 0, 0.421358,-0.0504957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546372,0.00541873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748,0.0365666) , 
9, 0.975609, 1, 0, 0.573842,0.0474213) , 
5, 0.943427, 1, 0, 0.5,3.9252e-06)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522044,0.00452755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403325,-0.0176125) , 
7, 0.421418, 1, 0, 0.478815,-0.0174018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718182,0.0373152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592965,0.0142639) , 
13, 1.24344, 1, 0, 0.658711,0.130401) , 
3, 930.418, 1, 0, 0.5,3.80452e-06)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33419,-0.0232779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516315,0.00115275) , 
5, 0.938629, 1, 0, 0.438462,-0.0456778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495845,0.000487615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677863,0.0251278) , 
10, 0.535253, 1, 0, 0.564442,0.0478447) , 
14, 0.604709, 1, 0, 0.5,5.77527e-06)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444283,-0.00769359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578977,0.0117116) , 
3, 534.275, 1, 0, 0.520305,0.0161447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425414,-0.0121649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275556,-0.0363942) , 
7, 0.31213, 1, 0, 0.342365,-0.125293) , 
12, 0.94468, 1, 0, 0.5,5.41581e-06)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0308164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551838,0.00807241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415796,-0.012934) , 
4, 2.42449, 1, 0, 0.516149,0.0126897) , 
1, 42.5212, 1, 0, 0.5,1.62945e-06)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421196,-0.0101135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248804,-0.0379948) , 
11, 0.801299, 1, 0, 0.358752,-0.0987196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546749,0.00654595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308642,-0.0263763) , 
4, 2.75497, 1, 0, 0.52734,0.0191056) , 
5, 0.911398, 1, 0, 0.5,-2.12064e-06)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243781,-0.0359441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463404,-0.00284028) , 
1, 42.5212, 1, 0, 0.445817,-0.0267582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700855,0.0264657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572414,0.00250293) , 
7, 0.328582, 1, 0, 0.629771,0.0640508) , 
9, 0.919751, 1, 0, 0.5,-1.06235e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522044,0.00374489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403325,-0.0149211) , 
7, 0.421418, 1, 0, 0.478815,-0.014846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578431,0.0120182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734884,0.033212) , 
9, 0.883959, 1, 0, 0.658711,0.111144) , 
3, 930.418, 1, 0, 0.5,-9.01812e-06)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368373,-0.0147966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524532,0.00198073) , 
5, 0.943427, 1, 0, 0.447404,-0.0306999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505682,0.000361586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676056,0.0216498) , 
14, 0.610488, 1, 0, 0.586746,0.0506207) , 
10, 0.535253, 1, 0, 0.5,-4.66476e-06)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502234,0.000733418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311828,-0.0260918) , 
12, 0.946897, 1, 0, 0.480646,-0.0110607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.0275925) , 
9, 0.972611, 1, 0, 0.5,-2.23842e-06)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361017,-0.0187634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476651,-0.00262918) , 
14, 0.605599, 1, 0, 0.420314,-0.0510096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575827,0.0109037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438449,-0.0108351) , 
7, 0.495894, 1, 0, 0.541116,0.0263186) , 
10, 0.326269, 1, 0, 0.5,-8.05768e-07)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332689,-0.0204788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507628,0.000733243) , 
5, 0.911926, 1, 0, 0.478815,-0.0133015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718182,0.0297257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592965,0.0106288) , 
13, 1.24344, 1, 0, 0.658711,0.0996302) , 
3, 930.418, 1, 0, 0.5,-2.38327e-06)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0256371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551838,0.00647135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415796,-0.0102338) , 
4, 2.42449, 1, 0, 0.516149,0.0102941) , 
1, 42.5212, 1, 0, 0.5,-1.91103e-06)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502627,0.00263919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345753,-0.0201342) , 
7, 0.328582, 1, 0, 0.417874,-0.0461484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466606,-0.00377897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613246,0.013154) , 
10, 0.395931, 1, 0, 0.544041,0.0247396) , 
14, 0.537186, 1, 0, 0.5,-5.44441e-06)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40625,-0.0104348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538838,0.0045023) , 
3, 534.275, 1, 0, 0.480646,-0.00978755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.0248382) , 
9, 0.972611, 1, 0, 0.5,-6.39386e-06)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462283,-0.00351744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615966,0.0122226) , 
10, 0.535253, 1, 0, 0.520305,0.0113817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425414,-0.00870325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275556,-0.0269429) , 
7, 0.31213, 1, 0, 0.342365,-0.088383) , 
12, 0.94468, 1, 0, 0.5,-2.35108e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421196,-0.00680813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248804,-0.029973) , 
11, 0.801299, 1, 0, 0.358752,-0.0715372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492469,-0.00170689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624051,0.0155639) , 
14, 0.705993, 1, 0, 0.52734,0.0138421) , 
5, 0.911398, 1, 0, 0.5,-3.87755e-06)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53394,0.00545837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432749,-0.00893199) , 
7, 0.328582, 1, 0, 0.478815,-0.0113077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578431,0.00885555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734884,0.0266846) , 
9, 0.883959, 1, 0, 0.658711,0.0846569) , 
3, 930.418, 1, 0, 0.5,-6.62028e-06)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0224434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405775,-0.0109948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543826,0.00502496) , 
14, 0.469664, 1, 0, 0.516149,0.00885855) , 
1, 42.5212, 1, 0, 0.5,-2.18865e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40625,-0.00899978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538838,0.00378019) , 
3, 534.275, 1, 0, 0.480646,-0.00863844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.0223065) , 
9, 0.972611, 1, 0, 0.5,-5.62646e-06)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510007,0.0016087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664251,0.0202326) , 
10, 0.674576, 1, 0, 0.544283,0.0273148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325,-0.0229328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485393,-0.00179623) , 
10, 0.257386, 1, 0, 0.451327,-0.0300263) , 
13, 1.32755, 1, 0, 0.5,-2.02714e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496583,0.00220838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389774,-0.0105293) , 
13, 1.32755, 1, 0, 0.445817,-0.0182248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710594,0.0220299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582451,0.00189126) , 
7, 0.282163, 1, 0, 0.629771,0.0436419) , 
9, 0.919751, 1, 0, 0.5,-2.11081e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.0230566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399317,-0.00321439) , 
9, 0.833634, 1, 0, 0.358752,-0.0613557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492469,-0.00155979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624051,0.0137186) , 
14, 0.705993, 1, 0, 0.52734,0.0118775) , 
5, 0.911398, 1, 0, 0.5,1.30578e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450925,-0.00249578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630105,0.0136396) , 
9, 0.875701, 1, 0, 0.549359,0.0301264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399687,-0.0110776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570637,0.00575157) , 
14, 0.672232, 1, 0, 0.461461,-0.0235212) , 
7, 0.32372, 1, 0, 0.5,4.826e-07)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0199532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495868,-0.000470547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671958,0.018089) , 
3, 951.455, 1, 0, 0.516149,0.00774206) , 
1, 42.5212, 1, 0, 0.5,1.4189e-06)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449108,-0.00465062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313953,-0.0193561) , 
12, 0.799708, 1, 0, 0.420314,-0.0368418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575827,0.00823267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438449,-0.00853948) , 
7, 0.495894, 1, 0, 0.541116,0.0190115) , 
10, 0.326269, 1, 0, 0.5,1.30422e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494077,-0.000465062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722071,0.0192204) , 
9, 0.963801, 1, 0, 0.519926,0.0078525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299065,-0.0174889) , 
4, 2.7472, 1, 0, 0.5,-4.34701e-07)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447816,-0.00484896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642623,0.0143327) , 
3, 930.418, 1, 0, 0.469211,-0.0131602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709184,0.0268191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576068,0.00440206) , 
7, 0.213578, 1, 0, 0.609475,0.046799) , 
10, 0.674576, 1, 0, 0.5,1.19801e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486388,-0.00124302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6411,0.0131208) , 
10, 0.674576, 1, 0, 0.520305,0.00873723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278027,-0.0213735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420765,-0.00713221) , 
8, 0.965193, 1, 0, 0.342365,-0.0677882) , 
12, 0.94468, 1, 0, 0.5,4.98647e-06)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0180062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405775,-0.00894856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543826,0.00402645) , 
14, 0.469664, 1, 0, 0.516149,0.00690215) , 
1, 42.5212, 1, 0, 0.5,3.65202e-06)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.0205204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399317,-0.00203864) , 
9, 0.833634, 1, 0, 0.358752,-0.0517342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440239,-0.00574503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571573,0.00620202) , 
10, 0.326269, 1, 0, 0.52734,0.0100142) , 
5, 0.911398, 1, 0, 0.5,4.66656e-07)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492758,-0.000514421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754717,0.0219381) , 
9, 0.972611, 1, 0, 0.513345,0.00527519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258065,-0.0218196) , 
4, 2.90856, 1, 0, 0.5,-1.66007e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599232,0.0126416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499358,-0.00216398) , 
13, 1.23687, 1, 0, 0.549359,0.0248493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399687,-0.0091604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570637,0.00459558) , 
14, 0.672232, 1, 0, 0.461461,-0.0194014) , 
7, 0.32372, 1, 0, 0.5,2.58601e-07)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525,0.00341145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41035,-0.0083513) , 
7, 0.328582, 1, 0, 0.463841,-0.0132338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544966,0.00275553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.746888,0.0227317) , 
9, 0.936223, 1, 0, 0.59432,0.0345212) , 
2, 892.574, 1, 0, 0.5,1.29793e-07)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0161369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536904,0.00297839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352304,-0.0125422) , 
12, 0.94468, 1, 0, 0.516149,0.00610306) , 
1, 42.5212, 1, 0, 0.5,3.33222e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422018,-0.0197408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483054,-0.000167623) , 
13, 0.586164, 1, 0, 0.478815,-0.00727817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718182,0.0184321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592965,0.00503832) , 
13, 1.24344, 1, 0, 0.658711,0.0545242) , 
3, 930.418, 1, 0, 0.5,-1.49556e-07)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.018437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399317,-0.00149982) , 
9, 0.833634, 1, 0, 0.358752,-0.0451334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411248,-0.00942977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554726,0.00449542) , 
14, 0.469664, 1, 0, 0.52734,0.00873914) , 
5, 0.911398, 1, 0, 0.5,2.64669e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270718,-0.0223488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45641,-0.0040066) , 
5, 0.928816, 1, 0, 0.397548,-0.0452879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492611,7.98864e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724138,0.0164352) , 
9, 0.963801, 1, 0, 0.519585,0.00865721) , 
10, 0.221777, 1, 0, 0.5,-7.72532e-08)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663889,0.0183367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470297,-0.00109903) , 
6, 0.00176209, 1, 0, 0.561518,0.0369749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435252,-0.00632395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59316,0.00730832) , 
14, 0.705993, 1, 0, 0.483178,-0.0101101) , 
7, 0.183424, 1, 0, 0.5,3.54487e-07)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0146713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405959,-0.00849961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537705,0.00308757) , 
10, 0.223518, 1, 0, 0.516149,0.00548696) , 
1, 42.5212, 1, 0, 0.5,2.62305e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492758,-0.00039719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754717,0.0180738) , 
9, 0.972611, 1, 0, 0.513345,0.00425813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258065,-0.018175) , 
4, 2.90856, 1, 0, 0.5,2.48495e-07)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361301,-0.0127967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526316,0.00753435) , 
14, 0.698828, 1, 0, 0.404792,-0.0337113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547862,0.00399952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364516,-0.0136712) , 
13, 2.06894, 1, 0, 0.527306,0.00967023) , 
3, 435.24, 1, 0, 0.5,1.43334e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512085,0.00487283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419833,-0.00638563) , 
7, 0.230189, 1, 0, 0.447404,-0.0139875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561145,0.00236762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742105,0.0221224) , 
14, 0.776668, 1, 0, 0.586746,0.0230661) , 
10, 0.535253, 1, 0, 0.5,-1.28006e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469697,-0.0134539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565762,0.00760016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45342,-0.00401975) , 
13, 1.25703, 1, 0, 0.502429,0.00505548) , 
13, 0.586164, 1, 0, 0.5,1.26537e-06)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429185,-0.0175909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489682,0.000181998) , 
13, 0.586164, 1, 0, 0.485393,-0.00509575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676471,0.0137183) , 
3, 1029.45, 1, 0, 0.5,1.86471e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486388,-0.00112658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6411,0.0103305) , 
10, 0.674576, 1, 0, 0.520305,0.00612096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278027,-0.0162162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420765,-0.00445818) , 
8, 0.965193, 1, 0, 0.342365,-0.0474924) , 
12, 0.94468, 1, 0, 0.5,3.19212e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421196,-0.0022376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248804,-0.0200075) , 
11, 0.801299, 1, 0, 0.358752,-0.0374918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411248,-0.00804257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554726,0.00379871) , 
14, 0.469664, 1, 0, 0.52734,0.0072598) , 
5, 0.911398, 1, 0, 0.5,2.45092e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457143,-0.0198849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525463,-0.000223649) , 
13, 0.912905, 1, 0, 0.500739,-0.0342078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633962,0.0188936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486239,-7.59286e-06) , 
12, 0.350987, 1, 0, 0.499826,0.00803712) , 
12, 0.292307, 1, 0, 0.5,-1.04927e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0129632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495868,-0.000358736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671958,0.0122101) , 
3, 951.455, 1, 0, 0.516149,0.00477644) , 
1, 42.5212, 1, 0, 0.5,1.12937e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663889,0.0161951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470297,-0.00125808) , 
6, 0.00176209, 1, 0, 0.561518,0.031437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435252,-0.00517855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59316,0.00570258) , 
14, 0.705993, 1, 0, 0.483178,-0.00859478) , 
7, 0.183424, 1, 0, 0.5,1.14568e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337243,-0.0123462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452874,-0.00189339) , 
3, 441.937, 1, 0, 0.420314,-0.0221701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575827,0.00560422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438449,-0.00680518) , 
7, 0.495894, 1, 0, 0.541116,0.0114438) , 
10, 0.326269, 1, 0, 0.5,2.95835e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457143,-0.0181635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525463,-0.000324713) , 
13, 0.912905, 1, 0, 0.500739,-0.0315919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482534,-1.55965e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663043,0.0170589) , 
14, 0.790618, 1, 0, 0.499826,0.00742591) , 
12, 0.292307, 1, 0, 0.5,1.78023e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469697,-0.0100641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556598,0.00536146) , 
13, 0.586077, 1, 0, 0.544283,0.0147601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325,-0.0146854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485393,-0.000592925) , 
10, 0.257386, 1, 0, 0.451327,-0.0162148) , 
13, 1.32755, 1, 0, 0.5,3.93087e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.0118598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423631,-0.0042405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559125,0.00336593) , 
9, 0.858081, 1, 0, 0.516149,0.0043285) , 
1, 42.5212, 1, 0, 0.5,1.98844e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53202,-0.00723879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.0107112) , 
12, 0.37653, 1, 0, 0.561518,0.0278135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405316,-0.00677006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542138,0.00213905) , 
3, 534.275, 1, 0, 0.483178,-0.00760467) , 
7, 0.183424, 1, 0, 0.5,5.92061e-07)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486388,-0.000997014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6411,0.00898643) , 
10, 0.674576, 1, 0, 0.520305,0.00517998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334821,-0.00384828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351648,-0.015681) , 
10, 0.474064, 1, 0, 0.342365,-0.0402127) , 
12, 0.94468, 1, 0, 0.5,2.66418e-07)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385027,-0.0177759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45071,-0.000686111) , 
13, 0.586164, 1, 0, 0.445817,-0.00920111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710594,0.0131747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582451,0.000326046) , 
7, 0.282163, 1, 0, 0.629771,0.0220391) , 
9, 0.919751, 1, 0, 0.5,6.27145e-07)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431741,-0.00359875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577082,0.00388813) , 
10, 0.535253, 1, 0, 0.485393,-0.00405083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676471,0.0111375) , 
3, 1029.45, 1, 0, 0.5,2.40261e-06)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420765,-0.00723887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574482,0.00539235) , 
9, 0.840217, 1, 0, 0.544283,0.0133434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386986,-0.00659369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593928,0.00422354) , 
5, 0.959682, 1, 0, 0.451327,-0.0146595) , 
13, 1.32755, 1, 0, 0.5,3.07077e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457143,-0.0161697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525463,-0.000172583) , 
13, 0.912905, 1, 0, 0.500739,-0.0276684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633962,0.0165966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486239,-0.000116712) , 
12, 0.350987, 1, 0, 0.499826,0.00650452) , 
12, 0.292307, 1, 0, 0.5,2.24856e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376364,-0.00879512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533333,0.00589948) , 
3, 612.701, 1, 0, 0.438462,-0.0131053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602177,0.00795368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530187,-0.00149704) , 
7, 0.34773, 1, 0, 0.564442,0.0137306) , 
14, 0.604709, 1, 0, 0.5,3.39901e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383893,-0.00722118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509069,0.00100553) , 
3, 435.24, 1, 0, 0.480646,-0.00380589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.010979) , 
9, 0.972611, 1, 0, 0.5,2.27116e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606061,0.0141095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50547,-0.000491552) , 
4, 1.40089, 1, 0, 0.513345,0.00302353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258065,-0.0135363) , 
4, 2.90856, 1, 0, 0.5,2.61769e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.0140716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399317,0.000923148) , 
9, 0.833634, 1, 0, 0.358752,-0.0284507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411248,-0.00675312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554726,0.00304999) , 
14, 0.469664, 1, 0, 0.52734,0.00550872) , 
5, 0.911398, 1, 0, 0.5,1.53544e-06)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457143,-0.0151421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525463,-0.000216033) , 
13, 0.912905, 1, 0, 0.500739,-0.026024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482534,-5.48637e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663043,0.0146716) , 
14, 0.790618, 1, 0, 0.499826,0.00611501) , 
12, 0.292307, 1, 0, 0.5,-2.60735e-07)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53202,-0.0069801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.00965921) , 
12, 0.37653, 1, 0, 0.561518,0.0243108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465497,-0.00260024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681223,0.0119326) , 
3, 1029.45, 1, 0, 0.483178,-0.00664586) , 
7, 0.183424, 1, 0, 0.5,1.38649e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465863,0.00137539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34472,-0.0122117) , 
12, 0.492849, 1, 0, 0.397548,-0.0283124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573991,0.00512155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47544,-0.00204143) , 
7, 0.328582, 1, 0, 0.519585,0.00541529) , 
10, 0.221777, 1, 0, 0.5,2.55538e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.00996805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536904,0.00182787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352304,-0.00800221) , 
12, 0.94468, 1, 0, 0.516149,0.00356588) , 
1, 42.5212, 1, 0, 0.5,1.56017e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473868,-0.00229738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60479,0.00675852) , 
10, 0.395931, 1, 0, 0.544283,0.0113912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325,-0.0120308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485393,-0.00034792) , 
10, 0.257386, 1, 0, 0.451327,-0.0125202) , 
13, 1.32755, 1, 0, 0.5,9.7603e-09)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435685,-0.0118716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484211,0.000147866) , 
13, 0.586164, 1, 0, 0.480646,-0.00343953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.010027) , 
9, 0.972611, 1, 0, 0.5,-6.66578e-07)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457143,-0.0136388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525463,-0.000193092) , 
13, 0.912905, 1, 0, 0.500739,-0.0233847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633962,0.0145081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486239,-0.000133028) , 
12, 0.350987, 1, 0, 0.499826,0.00549561) , 
12, 0.292307, 1, 0, 0.5,4.07801e-07)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420765,-0.00621859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574482,0.00449938) , 
9, 0.840217, 1, 0, 0.544283,0.0108726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325,-0.011013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485393,-0.000470836) , 
10, 0.257386, 1, 0, 0.451327,-0.0119473) , 
13, 1.32755, 1, 0, 0.5,1.378e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.00909928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495868,-0.000321305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671958,0.00911061) , 
3, 951.455, 1, 0, 0.516149,0.00323041) , 
1, 42.5212, 1, 0, 0.5,2.0442e-07)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64,0.017451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522323,0.000188296) , 
4, 1.41659, 1, 0, 0.531711,0.00717127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379469,-0.00781672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63587,0.014654) , 
2, 1067.35, 1, 0, 0.424358,-0.0171048) , 
7, 0.464017, 1, 0, 0.5,3.59012e-07)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421196,-0.00031636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248804,-0.016126) , 
11, 0.801299, 1, 0, 0.358752,-0.0245967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528497,0.0140541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52726,0.000135086) , 
8, 0.914249, 1, 0, 0.52734,0.00476188) , 
5, 0.911398, 1, 0, 0.5,8.03006e-07)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537954,0.00242575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.0106148) , 
12, 0.18183, 1, 0, 0.500739,-0.0219666) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563492,0.00676825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471736,-0.00138246) , 
7, 0.235582, 1, 0, 0.499826,0.00515987) , 
12, 0.292307, 1, 0, 0.5,-1.62394e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376364,-0.0072639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533333,0.00493305) , 
3, 612.701, 1, 0, 0.438462,-0.010508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602177,0.00643198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530187,-0.00119717) , 
7, 0.34773, 1, 0, 0.564442,0.0110017) , 
14, 0.604709, 1, 0, 0.5,-1.02506e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435685,-0.0110415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484211,0.000157255) , 
13, 0.586164, 1, 0, 0.480646,-0.00309759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.00911732) , 
9, 0.972611, 1, 0, 0.5,-1.47421e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486388,-0.000864492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6411,0.00706966) , 
10, 0.674576, 1, 0, 0.520305,0.00367247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334821,-0.00078737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351648,-0.0137767) , 
10, 0.474064, 1, 0, 0.342365,-0.0285159) , 
12, 0.94468, 1, 0, 0.5,-5.15656e-07)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475958,-0.00139968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682482,0.0095774) , 
3, 1001.61, 1, 0, 0.49284,-0.00247571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616505,0.00889186) , 
14, 0.841038, 1, 0, 0.5,-2.90284e-07)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457143,-0.0125517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525463,9.30472e-05) , 
13, 0.912905, 1, 0, 0.500739,-0.0206152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633962,0.012756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486239,-0.000101567) , 
12, 0.350987, 1, 0, 0.499826,0.00484525) , 
12, 0.292307, 1, 0, 0.5,7.58428e-07)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606061,0.0116915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50547,-0.000433374) , 
4, 1.40089, 1, 0, 0.513345,0.00234386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258065,-0.0108311) , 
4, 2.90856, 1, 0, 0.5,1.49356e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.00809557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508244,-1.90818e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645503,0.0112682) , 
14, 0.841038, 1, 0, 0.516149,0.00284447) , 
1, 42.5212, 1, 0, 0.5,9.0641e-07)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435685,-0.0101102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484211,0.000150473) , 
13, 0.586164, 1, 0, 0.480646,-0.00279957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729242,0.0083128) , 
9, 0.972611, 1, 0, 0.5,7.27198e-07)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473868,-0.00222256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60479,0.00579246) , 
10, 0.395931, 1, 0, 0.544283,0.0090837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386986,-0.00492184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593928,0.00368252) , 
5, 0.959682, 1, 0, 0.451327,-0.00998129) , 
13, 1.32755, 1, 0, 0.5,1.30881e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479167,0.00108276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52901,-0.0112501) , 
3, 614.3, 1, 0, 0.500739,-0.0192723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482534,-0.000123004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663043,0.0118905) , 
14, 0.790618, 1, 0, 0.499826,0.00453038) , 
12, 0.292307, 1, 0, 0.5,1.30873e-06)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663889,0.0118016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470297,-0.00251041) , 
6, 0.00176209, 1, 0, 0.561518,0.0180218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317972,-0.0133206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49709,-0.000100553) , 
5, 0.895265, 1, 0, 0.483178,-0.00492443) , 
7, 0.183424, 1, 0, 0.5,2.75207e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31713,-0.0125023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518248,0.00807588) , 
3, 612.701, 1, 0, 0.395184,-0.0186052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359477,-0.00839505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545954,0.00213726) , 
5, 0.903391, 1, 0, 0.525947,0.00460895) , 
14, 0.469664, 1, 0, 0.5,2.66681e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307971,-0.00740846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534341,0.00143855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372973,-0.00661929) , 
13, 2.06894, 1, 0, 0.516149,0.00258212) , 
1, 42.5212, 1, 0, 0.5,8.07879e-08)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34375,-0.00927604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484018,0.00307015) , 
0, 91.4385, 1, 0, 0.397548,-0.0197738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547405,0.00236598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420732,-0.00472838) , 
7, 0.514255, 1, 0, 0.519585,0.00377913) , 
10, 0.221777, 1, 0, 0.5,-7.19982e-07)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537954,0.0025516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.00907282) , 
12, 0.18183, 1, 0, 0.500739,-0.0176754) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563492,0.00579163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471736,-0.00125459) , 
7, 0.235582, 1, 0, 0.499826,0.00415165) , 
12, 0.292307, 1, 0, 0.5,-1.50348e-06)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
