// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : gsmith
Date           : Tue May 28 10:15:27 2013
Host           : Linux lxbuild167.cern.ch 2.6.18-308.1.1.el5 #1 SMP Wed Mar 7 19:25:07 CET 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/gsmith/cms_work/CMSSW_5_2_6/src/AnalysisCode/LeptonPlusJets/macros/tmva
Training events: 1402
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "4" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "1402" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [1.21145260334,3.18938326836]
sphericity                    sphericity                    sphericity                    sphericity                    sphericity                        'F'    [0.044630985707,0.864287316799]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.780373394489,0.998106598854]
closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass         'F'    [25.3397521973,367.574432373]
h3                            h3                            h3                            h3                            h3                                'F'    [-0.00260633416474,0.838969051838]
invariant_mass_of_everything  invariant_mass_of_everything  invariant_mass_of_everything  invariant_mass_of_everything  invariant_mass_of_everything      'F'    [398.96585083,3058.19799805]
best_higgs_mass               best_higgs_mass               best_higgs_mass               best_higgs_mass               best_higgs_mass                   'F'    [32.1661071777,1491.29541016]
dRbb                          dRbb                          dRbb                          dRbb                          dRbb                              'F'    [0.516629636288,4.94251298904]
maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                    'F'    [0.206517919898,4.07717466354]
maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                    'F'    [0.209698289633,4.7762799263]
abs(dEta_leptop_bb)           abs_dEta_leptop_bb_           abs(dEta_leptop_bb)           abs_dEta_leptop_bb            abs_dEta_leptop_bb                'F'    [0.000159473842359,5.4185090065]
abs(dEta_hadtop_bb)           abs_dEta_hadtop_bb_           abs(dEta_hadtop_bb)           abs_dEta_hadtop_bb            abs_dEta_hadtop_bb                'F'    [0.00274918717332,6.05968236923]
dEta_fn                       dEta_fn                       dEta_fn                       dEta_fn                       dEta_fn                           'F'    [0.00717877224088,4.8181385994]
median_bb_mass                median_bb_mass                median_bb_mass                median_bb_mass                median_bb_mass                    'F'    [58.0613861084,617.237487793]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.261261343956,0.95207965374]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "avg_dr_tagged_jets", "sphericity", "avg_btag_disc_btags", "closest_tagged_dijet_mass", "h3", "invariant_mass_of_everything", "best_higgs_mass", "dRbb", "maxeta_jet_tag", "maxeta_tag_tag", "abs(dEta_leptop_bb)", "abs(dEta_hadtop_bb)", "dEta_fn", "median_bb_mass", "pt_all_jets_over_E_all_jets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 1.21145260334015;
      fVmax[0] = 3.18938326835632;
      fVmin[1] = 0.0446309857070446;
      fVmax[1] = 0.864287316799164;
      fVmin[2] = 0.780373394489288;
      fVmax[2] = 0.998106598854065;
      fVmin[3] = 25.3397521972656;
      fVmax[3] = 367.574432373047;
      fVmin[4] = -0.00260633416473866;
      fVmax[4] = 0.838969051837921;
      fVmin[5] = 398.965850830078;
      fVmax[5] = 3058.19799804688;
      fVmin[6] = 32.1661071777344;
      fVmax[6] = 1491.29541015625;
      fVmin[7] = 0.516629636287689;
      fVmax[7] = 4.94251298904419;
      fVmin[8] = 0.206517919898033;
      fVmax[8] = 4.0771746635437;
      fVmin[9] = 0.209698289632797;
      fVmax[9] = 4.77627992630005;
      fVmin[10] = 0.000159473842359148;
      fVmax[10] = 5.41850900650024;
      fVmin[11] = 0.00274918717332184;
      fVmax[11] = 6.05968236923218;
      fVmin[12] = 0.00717877224087715;
      fVmax[12] = 4.81813859939575;
      fVmin[13] = 58.0613861083984;
      fVmax[13] = 617.237487792969;
      fVmin[14] = 0.261261343955994;
      fVmax[14] = 0.952079653739929;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551659,0.0103318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420601,-0.0158798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184211,-0.0631579) , 
4, 0.500912, 1, 0, 0.342939,-0.157061) , 
0, 2.3417, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551659,0.00929961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420601,-0.0142956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184211,-0.0570776) , 
4, 0.500912, 1, 0, 0.342939,-0.141369) , 
0, 2.3417, 1, 0, 0.5,-3.38582e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542081,0.0077947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527027,0.00551915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282511,-0.0405931) , 
1, 0.508793, 0, 0, 0.343434,-0.1449) , 
12, 1.61083, 1, 0, 0.5,-1.374e-05)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.024898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541045,0.00702615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359684,-0.0252721) , 
4, 0.358069, 1, 0, 0.452975,-0.0429977) , 
8, 1.1281, 1, 0, 0.5,-1.7859e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552821,0.00892531) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422857,-0.0125839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.0565439) , 
6, 310.095, 1, 0, 0.379391,-0.101699) , 
8, 1.86537, 1, 0, 0.5,-1.76555e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589404,0.0148055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53125,0.00477909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324607,-0.0288933) , 
14, 0.653053, 0, 0, 0.432331,-0.0559606) , 
4, 0.317994, 1, 0, 0.5,-2.41933e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.0210227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541045,0.00529855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359684,-0.0207627) , 
4, 0.358069, 1, 0, 0.452975,-0.0361885) , 
8, 1.1281, 1, 0, 0.5,-2.82577e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534199,0.0054909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402235,-0.0158752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176471,-0.0528417) , 
9, 2.52333, 1, 0, 0.340081,-0.127625) , 
10, 2.06429, 1, 0, 0.5,-2.75307e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542081,0.00579578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385246,-0.0133329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150943,-0.0614057) , 
7, 1.28415, 0, 0, 0.343434,-0.107269) , 
12, 1.61083, 1, 0, 0.5,-3.48949e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523163,0.0037905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4375,-0.00937344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209302,-0.0493134) , 
5, 1179.24, 1, 0, 0.306667,-0.157047) , 
1, 0.200756, 0, 0, 0.5,-4.04368e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.0181195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587629,0.0120723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400799,-0.0134891) , 
4, 0.237844, 1, 0, 0.452975,-0.031054) , 
8, 1.1281, 1, 0, 0.5,-4.45732e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00606081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476744,-0.00862657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.049922) , 
13, 159.704, 1, 0, 0.413994,-0.0923784) , 
3, 57.9335, 0, 0, 0.5,-3.83433e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551659,0.00572581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449367,-0.000352537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253968,-0.0329805) , 
1, 0.38635, 0, 0, 0.342939,-0.0864726) , 
0, 2.3417, 1, 0, 0.5,-4.00037e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00553276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476744,-0.00817562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.0451104) , 
13, 159.704, 1, 0, 0.413994,-0.0841992) , 
3, 57.9335, 0, 0, 0.5,-4.81163e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552821,0.00631543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422857,-0.00797894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.046465) , 
6, 310.095, 1, 0, 0.379391,-0.0714045) , 
8, 1.86537, 1, 0, 0.5,-5.0465e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534199,0.00433751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525424,0.00284491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281915,-0.0286309) , 
9, 1.40785, 1, 0, 0.340081,-0.10026) , 
10, 2.06429, 1, 0, 0.5,-5.67416e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523163,0.00315035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416667,-0.00010239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254902,-0.0397453) , 
2, 0.900454, 1, 0, 0.306667,-0.1298) , 
1, 0.200756, 0, 0, 0.5,-5.93901e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589404,0.0103746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565068,0.00749313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355731,-0.0172006) , 
14, 0.712858, 0, 0, 0.432331,-0.0389232) , 
4, 0.317994, 1, 0, 0.5,-5.95096e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00509582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476744,-0.0080229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.0406958) , 
13, 159.704, 1, 0, 0.413994,-0.0770959) , 
3, 57.9335, 0, 0, 0.5,-5.76168e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520527,0.00250532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303571,-0.0169017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218182,-0.0441834) , 
12, 1.16989, 0, 0, 0.261261,-0.143469) , 
7, 3.25646, 1, 0, 0.5,-5.94906e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602851,0.0113484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76,0.0425199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426249,-0.00909927) , 
4, 0.0975188, 1, 0, 0.444566,-0.0301541) , 
9, 1.29698, 1, 0, 0.5,-6.00283e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.0134608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510664,-0.000817836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305389,-0.0278965) , 
11, 2.31015, 1, 0, 0.476756,-0.0253514) , 
3, 106.824, 0, 0, 0.5,-4.96253e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543878,0.0051726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421788,-0.00673274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265625,-0.0434115) , 
1, 0.29113, 1, 0, 0.398104,-0.0590216) , 
1, 0.31785, 0, 0, 0.5,-5.01126e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00452816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.00981044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0442341) , 
13, 91.9422, 0, 0, 0.413994,-0.0682101) , 
3, 57.9335, 0, 0, 0.5,-4.75233e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534199,0.0036333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368159,-0.0118499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217391,-0.043489) , 
6, 99.7173, 0, 0, 0.340081,-0.0833046) , 
10, 2.06429, 1, 0, 0.5,-4.18587e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589404,0.00871419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544199,0.00407507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33945,-0.016131) , 
9, 1.51444, 1, 0, 0.432331,-0.0324885) , 
4, 0.317994, 1, 0, 0.5,-4.33571e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523163,0.00261132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4375,-0.00176503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209302,-0.039416) , 
5, 1179.24, 1, 0, 0.306667,-0.106436) , 
1, 0.200756, 0, 0, 0.5,-4.3549e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.0119966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52399,-4.34751e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305936,-0.0223453) , 
4, 0.478294, 1, 0, 0.476756,-0.0224642) , 
3, 106.824, 0, 0, 0.5,-4.83307e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556452,0.00873406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463866,-0.00745364) , 
6, 154.627, 1, 0, 0.51531,0.00753926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174603,-0.0375894) , 
7, 3.46722, 1, 0, 0.5,-4.93296e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00410026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.00872527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0410887) , 
13, 91.9422, 0, 0, 0.413994,-0.0613672) , 
3, 57.9335, 0, 0, 0.5,-5.21886e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.0120938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464535,-0.002647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170732,-0.0454964) , 
1, 0.122366, 0, 0, 0.452975,-0.0203229) , 
8, 1.1281, 1, 0, 0.5,-4.68868e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.00182275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534884,-0.00626477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208333,-0.0447359) , 
0, 2.27786, 1, 0, 0.362637,-0.127055) , 
3, 155.715, 1, 0, 0.5,-4.59207e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.0112156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.00106111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.0282591) , 
7, 0.938142, 0, 0, 0.476756,-0.0208917) , 
3, 106.824, 0, 0, 0.5,-4.65526e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601266,0.0122164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485139,-0.002154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116279,-0.0464112) , 
4, 0.678669, 1, 0, 0.470534,-0.0173663) , 
12, 0.465365, 1, 0, 0.5,-4.1797e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.0017234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534884,-0.00695073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208333,-0.04178) , 
0, 2.27786, 1, 0, 0.362637,-0.119962) , 
3, 155.715, 1, 0, 0.5,-4.60963e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.0106434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510664,-0.000555233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305389,-0.0228785) , 
11, 2.31015, 1, 0, 0.476756,-0.0197521) , 
3, 106.824, 0, 0, 0.5,-4.68085e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520527,0.00184613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303571,-0.00953028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218182,-0.0370047) , 
12, 1.16989, 0, 0, 0.261261,-0.104256) , 
7, 3.25646, 1, 0, 0.5,-4.64923e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00360983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476744,-0.00504403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223529,-0.0322849) , 
13, 159.704, 1, 0, 0.413994,-0.0536713) , 
3, 57.9335, 0, 0, 0.5,-4.75743e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534199,0.00287736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367647,0.00492892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329609,-0.0209671) , 
12, 2.57542, 0, 0, 0.340081,-0.0652637) , 
10, 2.06429, 1, 0, 0.5,-4.94411e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.00163975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534884,-0.00786673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208333,-0.0390225) , 
0, 2.27786, 1, 0, 0.362637,-0.113749) , 
3, 155.715, 1, 0, 0.5,-4.79528e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523163,0.00207956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416667,0.00657802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254902,-0.0305422) , 
2, 0.900454, 1, 0, 0.306667,-0.0840625) , 
1, 0.200756, 0, 0, 0.5,-4.83754e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532392,0.0034999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293706,-0.0196705) , 
1, 0.200756, 0, 0, 0.507053,0.00587107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327273,-0.0304093) , 
2, 0.842583, 0, 0, 0.5,-4.95044e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00987571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.000847511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.0254683) , 
7, 0.938142, 0, 0, 0.476756,-0.0182058) , 
3, 106.824, 0, 0, 0.5,-4.89404e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589404,0.00673264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.000767815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304348,-0.0175608) , 
12, 1.39791, 1, 0, 0.432331,-0.0248379) , 
4, 0.317994, 1, 0, 0.5,-4.43997e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.00153372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387755,-0.00816436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.038989) , 
10, 0.986097, 0, 0, 0.362637,-0.105916) , 
3, 155.715, 1, 0, 0.5,-4.46973e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00942577) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525862,0.00303721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410673,-0.0128262) , 
6, 149.932, 1, 0, 0.476756,-0.017311) , 
3, 106.824, 0, 0, 0.5,-3.97358e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602851,0.00771324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76,0.0356398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426249,-0.0066259) , 
4, 0.0975188, 1, 0, 0.444566,-0.0200961) , 
9, 1.29698, 1, 0, 0.5,-3.62636e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00328234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.00581544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326531,-0.0357572) , 
10, 0.214511, 0, 0, 0.413994,-0.0483193) , 
3, 57.9335, 0, 0, 0.5,-2.81595e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601266,0.0103199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481818,-0.00102391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354167,-0.0244388) , 
2, 0.862025, 0, 0, 0.470534,-0.0144769) , 
12, 0.465365, 1, 0, 0.5,-2.55828e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.0014543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387755,-0.00801536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0364529) , 
10, 0.986097, 0, 0, 0.362637,-0.0997641) , 
3, 155.715, 1, 0, 0.5,-2.28045e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504666,0.00166436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534247,-0.000192165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.048313) , 
7, 1.55479, 1, 0, 0.448276,-0.0875283) , 
0, 1.77658, 0, 0, 0.5,-2.05188e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.00937967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464535,-0.00201671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170732,-0.0380654) , 
1, 0.122366, 0, 0, 0.452975,-0.0154896) , 
8, 1.1281, 1, 0, 0.5,-1.63719e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556452,0.00722895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463866,-0.0064565) , 
6, 154.627, 1, 0, 0.51531,0.005547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174603,-0.0300137) , 
7, 3.46722, 1, 0, 0.5,-1.83516e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00892451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.000568169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.0243193) , 
7, 0.938142, 0, 0, 0.476756,-0.0162492) , 
3, 106.824, 0, 0, 0.5,-2.19461e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514372,0.00130116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.011897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15,-0.0373141) , 
14, 0.54485, 0, 0, 0.2625,-0.102425) , 
10, 3.09636, 1, 0, 0.5,-2.02427e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00294507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.00523647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0361484) , 
13, 91.9422, 0, 0, 0.413994,-0.0431175) , 
3, 57.9335, 0, 0, 0.5,-2.42914e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.00136029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387755,-0.00767684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0338118) , 
10, 0.986097, 0, 0, 0.362637,-0.0929056) , 
3, 155.715, 1, 0, 0.5,-2.25971e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555695,0.00436385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611765,0.011625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395753,-0.00907336) , 
14, 0.717241, 0, 0, 0.426202,-0.027838) , 
1, 0.395912, 0, 0, 0.5,-2.06976e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589404,0.00574487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.000600735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304348,-0.0150538) , 
12, 1.39791, 1, 0, 0.432331,-0.0209841) , 
4, 0.317994, 1, 0, 0.5,-1.92108e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00826631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.00058658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.0220721) , 
7, 0.938142, 0, 0, 0.476756,-0.0149583) , 
3, 106.824, 0, 0, 0.5,-2.09846e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613636,0.0156001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49789,-0.000279081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352941,-0.0207758) , 
3, 155.715, 1, 0, 0.488189,-0.00768447) , 
2, 0.967002, 0, 0, 0.5,-1.95825e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540967,0.00435013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404192,-0.00959885) , 
5, 1158.75, 1, 0, 0.507053,0.00470464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327273,-0.0248764) , 
2, 0.842583, 0, 0, 0.5,-1.77872e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00804057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525862,0.00254773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410673,-0.0108576) , 
6, 149.932, 1, 0, 0.476756,-0.0144982) , 
3, 106.824, 0, 0, 0.5,-1.76452e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504666,0.00147561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534247,0.000300745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.043203) , 
7, 1.55479, 1, 0, 0.448276,-0.0767543) , 
0, 1.77658, 0, 0, 0.5,-1.63332e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552821,0.00312483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433544,-0.00104933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225225,-0.0282066) , 
13, 217.826, 1, 0, 0.379391,-0.0340757) , 
8, 1.86537, 1, 0, 0.5,-1.42732e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.0026696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.00409572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326531,-0.0323056) , 
10, 0.214511, 0, 0, 0.413994,-0.0387604) , 
3, 57.9335, 0, 0, 0.5,-1.97235e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601266,0.00879896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0284577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463671,-0.00380363) , 
2, 0.978666, 0, 0, 0.470534,-0.0121811) , 
12, 0.465365, 1, 0, 0.5,-1.84617e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556452,0.00628339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463866,-0.00567563) , 
6, 154.627, 1, 0, 0.51531,0.00462032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174603,-0.0263082) , 
7, 3.46722, 1, 0, 0.5,-1.51389e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.0073836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.000330083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.021031) , 
7, 0.938142, 0, 0, 0.476756,-0.0132424) , 
3, 106.824, 0, 0, 0.5,-1.78489e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514372,0.00110471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0103376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15,-0.0329905) , 
14, 0.54485, 0, 0, 0.2625,-0.0860773) , 
10, 3.09636, 1, 0, 0.5,-1.68307e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564384,0.0065663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450637,-0.00602238) , 
6, 154.627, 1, 0, 0.511782,0.00371189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136364,-0.0335029) , 
4, 0.678669, 1, 0, 0.5,-2.0069e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504666,0.00134772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534247,-4.25459e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.0387566) , 
7, 1.55479, 1, 0, 0.448276,-0.0697299) , 
0, 1.77658, 0, 0, 0.5,-2.2808e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.00748284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458204,-0.0041005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383562,0.020828) , 
12, 2.53798, 1, 0, 0.452975,-0.0121724) , 
8, 1.1281, 1, 0, 0.5,-2.1067e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612903,0.0121488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494542,-0.000378239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303571,-0.0274417) , 
3, 172.012, 1, 0, 0.485966,-0.00726954) , 
1, 0.669131, 0, 0, 0.5,-2.08572e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00709791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.000383023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.0197129) , 
7, 0.938142, 0, 0, 0.476756,-0.0126695) , 
3, 106.824, 0, 0, 0.5,-1.96685e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519293,0.00235886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359223,-0.0170746) , 
3, 42.8161, 0, 0, 0.507053,0.0040894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327273,-0.0219563) , 
2, 0.842583, 0, 0, 0.5,-1.85002e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514372,0.0010392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0102619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15,-0.0309977) , 
14, 0.54485, 0, 0, 0.2625,-0.080714) , 
10, 3.09636, 1, 0, 0.5,-1.87039e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601266,0.00761826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65,0.0262194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463671,-0.00334782) , 
2, 0.978666, 0, 0, 0.470534,-0.0104681) , 
12, 0.465365, 1, 0, 0.5,-2.1265e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.0010849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369565,-0.00278479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355556,-0.0288185) , 
12, 0.859113, 0, 0, 0.362637,-0.0729623) , 
3, 155.715, 1, 0, 0.5,-1.77363e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589404,0.00459385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436879,-0.000772311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397849,-0.0247073) , 
11, 0.297419, 0, 0, 0.432331,-0.0165944) , 
4, 0.317994, 1, 0, 0.5,-1.61493e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54828,0.00299619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413534,0.00221827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412766,-0.0141129) , 
1, 0.252582, 1, 0, 0.413174,-0.025538) , 
1, 0.356881, 0, 0, 0.5,-1.34682e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504666,0.00123792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526316,0.00481433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372881,-0.0301814) , 
5, 806.663, 0, 0, 0.448276,-0.0636531) , 
0, 1.77658, 0, 0, 0.5,-1.24642e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597619,0.00602513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510708,0.0024808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373333,-0.011335) , 
5, 1066.94, 1, 0, 0.458248,-0.0122227) , 
14, 0.721807, 0, 0, 0.5,-1.06434e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00677021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510664,0.000121787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305389,-0.0172213) , 
11, 2.31015, 1, 0, 0.476756,-0.0120016) , 
3, 106.824, 0, 0, 0.5,-1.07098e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532392,0.00246219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293706,-0.0152883) , 
1, 0.200756, 0, 0, 0.507053,0.00364414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327273,-0.0197679) , 
2, 0.842583, 0, 0, 0.5,-1.24255e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00222336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.00282834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326531,-0.0299697) , 
10, 0.214511, 0, 0, 0.413994,-0.0318463) , 
3, 57.9335, 0, 0, 0.5,-1.42761e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601266,0.00713874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478422,0.000911527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447273,-0.0110003) , 
7, 1.35966, 0, 0, 0.470534,-0.00973388) , 
12, 0.465365, 1, 0, 0.5,-1.3764e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556452,0.00550903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463866,-0.00502895) , 
6, 154.627, 1, 0, 0.51531,0.00386487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174603,-0.0230615) , 
7, 3.46722, 1, 0, 0.5,-1.15873e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00617223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492688,-0.000298952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.0174039) , 
7, 0.938142, 0, 0, 0.476756,-0.010906) , 
3, 106.824, 0, 0, 0.5,-1.36588e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.00102483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534884,-0.00171144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208333,-0.0286115) , 
0, 2.27786, 1, 0, 0.362637,-0.0683914) , 
3, 155.715, 1, 0, 0.5,-1.30938e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534199,0.00171055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397959,0.00769848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302013,-0.0193442) , 
2, 0.907965, 1, 0, 0.340081,-0.0374805) , 
10, 2.06429, 1, 0, 0.5,-1.5618e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612903,0.0103251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496938,0.000136512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365385,-0.0178036) , 
2, 0.863319, 0, 0, 0.485966,-0.00610691) , 
1, 0.669131, 0, 0, 0.5,-1.75879e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636111,0.00619184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458204,-0.00371682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383562,0.0226609) , 
12, 2.53798, 1, 0, 0.452975,-0.00994265) , 
8, 1.1281, 1, 0, 0.5,-1.59893e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511503,-0.00020788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.0359162) , 
12, 2.62153, 1, 0, 0.511161,0.00351886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241379,-0.0201781) , 
11, 3.46385, 1, 0, 0.5,-1.715e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514372,0.000927779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.00957022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15,-0.0280407) , 
14, 0.54485, 0, 0, 0.2625,-0.0714588) , 
10, 3.09636, 1, 0, 0.5,-2.11496e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504666,0.00110831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534247,0.00164604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.0346229) , 
7, 1.55479, 1, 0, 0.448276,-0.0566286) , 
0, 1.77658, 0, 0, 0.5,-2.27206e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564384,0.00556131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450637,-0.00516275) , 
6, 154.627, 1, 0, 0.511782,0.00297805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136364,-0.0289549) , 
4, 0.678669, 1, 0, 0.5,-2.15479e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527856,0.00210701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.0029542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309524,-0.0307815) , 
13, 91.9422, 0, 0, 0.413994,-0.030007) , 
3, 57.9335, 0, 0, 0.5,-2.29289e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560102,0.00582482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510664,0.000222046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305389,-0.0155565) , 
11, 2.31015, 1, 0, 0.476756,-0.010233) , 
3, 106.824, 0, 0, 0.5,-2.18186e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509535,0.000942151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369565,-0.00108145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355556,-0.026418) , 
12, 0.859113, 0, 0, 0.362637,-0.0627061) , 
3, 155.715, 1, 0, 0.5,-2.19908e-05)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
