// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : flowers1
Date           : Tue Jun 30 15:26:04 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/flowers1/May2015/CMSSW_7_2_3/src/ttH-LeptonPlusJets/AnalysisCode/macros/TRAINHOUSE
Training events: 5728
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
first_jet_pt                  first_jet_pt                  first_jet_pt                  first_jet_pt                  first_jet_pt                      'F'    [45.0438270569,1232.97790527]
second_jet_pt                 second_jet_pt                 second_jet_pt                 second_jet_pt                 second_jet_pt                     'F'    [39.1075286865,876.033569336]
fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                     'F'    [31.5118656158,373.491973877]
h0                            h0                            h0                            h0                            h0                                'F'    [0.162858784199,0.44008487463]
h1                            h1                            h1                            h1                            h1                                'F'    [-0.171268105507,0.384086072445]
all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met               'F'    [303.939544678,3238.66186523]
HT                            HT                            HT                            HT                            HT                                'F'    [224.635742188,2738.52441406]
h3                            h3                            h3                            h3                            h3                                'F'    [-0.0043538780883,0.973237991333]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.0886220633984,0.813898682594]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [0.071942448616,0.811478495598]
fifth_highest_CSV             fifth_highest_CSV             fifth_highest_CSV             fifth_highest_CSV             fifth_highest_CSV                 'F'    [-10,0.773896694183]
maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                    'F'    [0.166975423694,1.89548242092]
Mlb                           Mlb                           Mlb                           Mlb                           Mlb                               'F'    [31.195892334,8891.97851562]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.217861577868,0.964041113853]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "first_jet_pt", "second_jet_pt", "fourth_jet_pt", "h0", "h1", "all_sum_pt_with_met", "HT", "h3", "third_highest_btag", "fourth_highest_btag", "fifth_highest_CSV", "maxeta_jet_jet", "Mlb", "pt_all_jets_over_E_all_jets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414116,-0.0171767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663984,0.0327968) , 
9, 0.494534, 1, 0, 0.444229,-0.0557711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558018,0.0116037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721625,0.044325) , 
8, 0.544351, 1, 0, 0.643392,0.143392) , 
5, 862.934, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393877,-0.019656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564503,0.0129258) , 
8, 0.641159, 1, 0, 0.444229,-0.050194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558018,0.0104447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721625,0.0399738) , 
8, 0.544351, 1, 0, 0.643392,0.12906) , 
5, 862.934, 1, 0, 0.5,2.1323e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414553,-0.0144436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608896,0.0178627) , 
6, 690.863, 1, 0, 0.465937,-0.0295221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626667,0.0198281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786223,0.0517838) , 
3, 0.39203, 1, 0, 0.711055,0.182966) , 
9, 0.494534, 1, 0, 0.5,6.61166e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315739,-0.0318623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474858,-0.00315865) , 
5, 583.382, 1, 0, 0.422222,-0.0631076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533643,0.00659174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.71897,0.0336827) , 
5, 862.934, 1, 0, 0.595035,0.0771399) , 
8, 0.537603, 1, 0, 0.5,1.35349e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3075,-0.0334199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440158,-0.00758656) , 
5, 503.01, 1, 0, 0.381557,-0.0945156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518868,0.00337208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74168,0.037358) , 
9, 0.494534, 1, 0, 0.554761,0.0437224) , 
6, 464.054, 1, 0, 0.5,1.61913e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322713,-0.0301338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461988,-0.00316011) , 
13, 0.679778, 1, 0, 0.370794,-0.10354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41782,-0.0112158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593001,0.0142855) , 
5, 583.437, 1, 0, 0.545262,0.0362966) , 
8, 0.330381, 1, 0, 0.5,1.90336e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429506,-0.0115231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572719,0.0158601) , 
13, 0.715315, 1, 0, 0.462715,-0.0256471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626531,0.0145611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.0384543) , 
3, 0.38728, 1, 0, 0.686583,0.128427) , 
6, 823.181, 1, 0, 0.5,1.40766e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372954,-0.0168927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560386,0.0083321) , 
6, 668.622, 1, 0, 0.422222,-0.0507635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532853,0.000501653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642127,0.0217957) , 
3, 0.38728, 1, 0, 0.595035,0.0620714) , 
8, 0.537603, 1, 0, 0.5,2.00778e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437451,-0.00953666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571544,0.0135634) , 
13, 0.710011, 1, 0, 0.470193,-0.0192094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670241,0.019341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802768,0.0446947) , 
13, 0.631496, 1, 0, 0.728097,0.147152) , 
9, 0.52975, 1, 0, 0.5,1.74904e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,0.00288745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34533,-0.0228993) , 
7, 0.181854, 1, 0, 0.370794,-0.0857076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41782,-0.0093893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593001,0.0119405) , 
5, 583.437, 1, 0, 0.545262,0.0300588) , 
8, 0.330381, 1, 0, 0.5,2.58483e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447904,-0.00825277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587891,0.0226539) , 
4, 0.18633, 1, 0, 0.463516,-0.0236818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0114895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.775244,0.0421242) , 
13, 0.679782, 1, 0, 0.647318,0.0957261) , 
10, 0.260854, 1, 0, 0.5,2.05022e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509827,0.00500049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408969,-0.0148386) , 
7, 0.368062, 1, 0, 0.462715,-0.0209844) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626531,0.0120753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.0323088) , 
3, 0.38728, 1, 0, 0.686583,0.105159) , 
6, 823.181, 1, 0, 0.5,2.47699e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3075,-0.0260796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440158,-0.00360268) , 
5, 503.01, 1, 0, 0.381557,-0.0661524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498621,-0.00347486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603137,0.0147201) , 
3, 0.38728, 1, 0, 0.554761,0.0306278) , 
6, 464.054, 1, 0, 0.5,2.91995e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437451,-0.00832992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571544,0.0125647) , 
13, 0.710011, 1, 0, 0.470193,-0.0158045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653846,0.0135021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794286,0.0368187) , 
3, 0.39203, 1, 0, 0.728097,0.121139) , 
9, 0.52975, 1, 0, 0.5,2.2333e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311441,-0.0222504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47417,-0.00169084) , 
6, 566.333, 1, 0, 0.370794,-0.0716455) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531769,0.00228595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659243,0.0292374) , 
4, 0.198968, 1, 0, 0.545262,0.0251383) , 
8, 0.330381, 1, 0, 0.5,2.99471e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550881,0.0135217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438699,-0.0083603) , 
7, 0.181854, 1, 0, 0.462715,-0.0179368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626531,0.0110769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.0275608) , 
3, 0.38728, 1, 0, 0.686583,0.0898894) , 
6, 823.181, 1, 0, 0.5,2.16787e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446714,-0.00840108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618538,0.0213393) , 
4, 0.198968, 1, 0, 0.468721,-0.022278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00141408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646681,0.0221937) , 
12, 151.566, 1, 0, 0.601632,0.0724967) , 
13, 0.715315, 1, 0, 0.5,2.58491e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410157,-0.00909913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6673,0.0182497) , 
6, 832.423, 1, 0, 0.444901,-0.0266116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527536,-0.00108811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670742,0.0196716) , 
10, 0.18368, 1, 0, 0.616894,0.0565397) , 
8, 0.641214, 1, 0, 0.5,2.64068e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262295,-0.0318548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411765,-0.00583776) , 
6, 338.641, 1, 0, 0.381557,-0.0535377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524353,0.00154961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701337,0.022815) , 
8, 0.744825, 1, 0, 0.554761,0.024796) , 
6, 464.054, 1, 0, 0.5,2.95621e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405749,-0.0153955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51303,0.00377583) , 
4, -0.0125955, 1, 0, 0.468721,-0.0199728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.000946164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646681,0.0199227) , 
12, 151.566, 1, 0, 0.601632,0.0650073) , 
13, 0.715315, 1, 0, 0.5,2.6004e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321033,-0.0205676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430906,-0.00246189) , 
12, 204.203, 1, 0, 0.370794,-0.0595143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491803,-0.00440869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585821,0.0110582) , 
3, 0.38728, 1, 0, 0.545262,0.0208818) , 
8, 0.330381, 1, 0, 0.5,2.48544e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553991,0.012226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447888,-0.00650687) , 
7, 0.181854, 1, 0, 0.470193,-0.0123393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670241,0.0112447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802768,0.0334434) , 
13, 0.631496, 1, 0, 0.728097,0.0945939) , 
9, 0.52975, 1, 0, 0.5,1.92198e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417468,-0.0119023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61706,0.0183612) , 
4, 0.198968, 1, 0, 0.453561,-0.0310055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483794,-0.00116647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614407,0.0150385) , 
12, 187.77, 1, 0, 0.552779,0.0352919) , 
13, 0.608718, 1, 0, 0.5,2.51421e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549949,0.0102144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440331,-0.00700611) , 
7, 0.181854, 1, 0, 0.463516,-0.0161378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57903,0.00499187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73494,0.0259932) , 
13, 0.608718, 1, 0, 0.647318,0.0652831) , 
10, 0.260854, 1, 0, 0.5,2.40959e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395525,-0.00997705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567404,0.0148277) , 
13, 0.750847, 1, 0, 0.422782,-0.0289362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565492,0.00274818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669553,0.0201008) , 
12, 341.073, 1, 0, 0.593292,0.0350197) , 
5, 723.186, 1, 0, 0.5,2.70473e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418301,-0.0121601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584179,0.011763) , 
12, 335.177, 1, 0, 0.451249,-0.0359921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493116,0.00214316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788066,0.0286581) , 
9, 0.493816, 1, 0, 0.537277,0.0275653) , 
3, 0.38728, 1, 0, 0.5,2.52234e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0271567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555118,0.00786075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469263,-0.0052205) , 
7, 0.368062, 1, 0, 0.513578,0.00743988) , 
5, 443.688, 1, 0, 0.5,3.14933e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445629,-0.00119533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6251,0.0148573) , 
8, 0.433958, 1, 0, 0.548196,0.0378638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435727,-0.00950017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614035,0.0145635) , 
12, 331.736, 1, 0, 0.470189,-0.0233803) , 
11, 0.825454, 1, 0, 0.5,2.46091e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465933,-0.00459365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563847,0.00946243) , 
3, 0.38728, 1, 0, 0.521522,0.0158566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315942,-0.0229404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551282,0.00175636) , 
1, 124.748, 1, 0, 0.427702,-0.0531583) , 
7, 0.507718, 1, 0, 0.5,2.46152e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311346,-0.0175325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432692,-0.00215558) , 
13, 0.614282, 1, 0, 0.370794,-0.0470598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459631,-0.00336399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604466,0.00828395) , 
2, 61.614, 1, 0, 0.545262,0.0165098) , 
8, 0.330381, 1, 0, 0.5,1.80709e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0240786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461959,-0.00513575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554054,0.00654834) , 
3, 0.38728, 1, 0, 0.513578,0.00645988) , 
5, 443.688, 1, 0, 0.5,1.38349e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528796,0.0034287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655814,0.0236329) , 
4, 0.18649, 1, 0, 0.574539,0.0512407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420496,-0.00714854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641925,0.00907777) , 
5, 878.258, 1, 0, 0.480371,-0.0134824) , 
7, 0.181854, 1, 0, 0.5,9.13719e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437398,-0.006179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636232,0.0136921) , 
8, 0.744825, 1, 0, 0.468721,-0.0146534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00129975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646681,0.0152434) , 
12, 151.566, 1, 0, 0.601632,0.047656) , 
13, 0.715315, 1, 0, 0.5,1.01779e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405733,-0.00931773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551468,0.00613815) , 
9, 0.177411, 1, 0, 0.521522,0.013873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315942,-0.0198693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551282,0.000975101) , 
1, 124.748, 1, 0, 0.427702,-0.0465488) , 
7, 0.507718, 1, 0, 0.5,1.2285e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482871,-0.00485503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573604,0.0112347) , 
4, -0.0585928, 1, 0, 0.548196,0.0319389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435727,-0.00822544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614035,0.0129723) , 
12, 331.736, 1, 0, 0.470189,-0.0197444) , 
11, 0.825454, 1, 0, 0.5,6.8103e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553991,0.00883027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447888,-0.00471452) , 
7, 0.181854, 1, 0, 0.470193,-0.00873867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669492,0.00596756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795455,0.0269824) , 
10, 0.348586, 1, 0, 0.728097,0.0669322) , 
9, 0.52975, 1, 0, 0.5,6.80909e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406071,-0.01154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0155134) , 
4, 0.225413, 1, 0, 0.444183,-0.0316843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493815,0.00135615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723127,0.0175847) , 
6, 832.423, 1, 0, 0.532871,0.0186778) , 
13, 0.537653, 1, 0, 0.5,1.18216e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418301,-0.00909698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584179,0.00881179) , 
12, 335.177, 1, 0, 0.451249,-0.0264997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489707,-0.00275301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583688,0.0112124) , 
4, -0.0126206, 1, 0, 0.537277,0.020287) , 
3, 0.38728, 1, 0, 0.5,1.38388e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292162,-0.0180768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499786,-0.000496831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637636,0.0150614) , 
13, 0.786379, 1, 0, 0.516488,0.00652091) , 
6, 344.345, 1, 0, 0.5,1.25957e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338889,-0.0126207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455665,0.00337354) , 
12, 260.626, 1, 0, 0.370794,-0.0383797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530249,0.000920853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63837,0.0149191) , 
4, 0.172523, 1, 0, 0.545262,0.0134583) , 
8, 0.330381, 1, 0, 0.5,1.01211e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447904,-0.00416056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587891,0.0123876) , 
4, 0.18633, 1, 0, 0.463516,-0.0109034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596378,0.00386644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.755495,0.0232425) , 
8, 0.740717, 1, 0, 0.647318,0.0440646) , 
10, 0.260854, 1, 0, 0.5,7.66944e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406071,-0.0102555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0118943) , 
4, 0.225413, 1, 0, 0.444183,-0.0296005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493815,0.00143438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723127,0.0158084) , 
6, 832.423, 1, 0, 0.532871,0.0174498) , 
13, 0.537653, 1, 0, 0.5,1.13018e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3075,-0.0156931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440158,8.89612e-05) , 
5, 503.01, 1, 0, 0.381557,-0.0313334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524353,0.000888564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701337,0.0145296) , 
8, 0.744825, 1, 0, 0.554761,0.0145054) , 
6, 464.054, 1, 0, 0.5,1.27365e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420579,-0.00856394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517582,0.00262305) , 
4, -0.0125955, 1, 0, 0.476543,-0.00968277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540881,-0.00266161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644543,0.0159575) , 
3, 0.388108, 1, 0, 0.611446,0.0460636) , 
13, 0.750847, 1, 0, 0.5,1.0563e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482871,-0.00422672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573604,0.00922399) , 
4, -0.0585928, 1, 0, 0.548196,0.025575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435727,-0.00679317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614035,0.0110548) , 
12, 331.736, 1, 0, 0.470189,-0.0158024) , 
11, 0.825454, 1, 0, 0.5,1.02995e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351764,-0.0137704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534451,0.00251191) , 
9, 0.277133, 1, 0, 0.444183,-0.0255479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500941,0.0015167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776978,0.0186243) , 
9, 0.52975, 1, 0, 0.532871,0.015061) , 
13, 0.537653, 1, 0, 0.5,9.88662e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.018066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461959,-0.00383912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554054,0.00486348) , 
3, 0.38728, 1, 0, 0.513578,0.00461001) , 
5, 443.688, 1, 0, 0.5,1.01836e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52093,0.00157886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0224728) , 
4, 0.172653, 1, 0, 0.582888,0.0487999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420495,-0.00799101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531844,0.00268222) , 
12, 181.496, 1, 0, 0.48755,-0.00732174) , 
7, 0.135302, 1, 0, 0.5,7.00322e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437398,-0.00449791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636232,0.0104604) , 
8, 0.744825, 1, 0, 0.468721,-0.0101942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00181834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646681,0.0112864) , 
12, 151.566, 1, 0, 0.601632,0.0331532) , 
13, 0.715315, 1, 0, 0.5,6.98344e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321033,-0.0122464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430906,0.000114306) , 
12, 204.203, 1, 0, 0.370794,-0.0302641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464506,-0.00719497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559822,0.00400977) , 
13, 0.431056, 1, 0, 0.545262,0.010613) , 
8, 0.330381, 1, 0, 0.5,8.36122e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262295,-0.0194507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479356,-0.000315864) , 
6, 338.643, 1, 0, 0.462715,-0.00787405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706177,0.0132841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653521,0.00186989) , 
1, 230.55, 1, 0, 0.686583,0.0394365) , 
6, 823.181, 1, 0, 0.5,5.53912e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659016,0.0199118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545557,0.00302756) , 
11, 0.751885, 1, 0, 0.574539,0.0343022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375393,-0.00768739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556784,0.00222115) , 
8, 0.436726, 1, 0, 0.480371,-0.00902807) , 
7, 0.181854, 1, 0, 0.5,4.10744e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384561,-0.00961334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539252,0.00275628) , 
2, 68.4019, 1, 0, 0.451249,-0.0197395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515546,0.000855587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6625,0.0174259) , 
13, 0.781654, 1, 0, 0.537277,0.0150996) , 
3, 0.38728, 1, 0, 0.5,3.48239e-06)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365809,-0.00778991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578125,0.00600674) , 
5, 520.295, 1, 0, 0.539315,0.0162755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386456,-0.0079703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634518,0.00656863) , 
6, 716.22, 1, 0, 0.457485,-0.0175931) , 
7, 0.368062, 1, 0, 0.5,3.44797e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396292,-0.00828403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532422,0.00238224) , 
13, 0.546566, 1, 0, 0.486931,-0.00541997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619893,0.0107872) , 
4, 0.198968, 1, 0, 0.5,2.25224e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447904,-0.00324872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587891,0.0100774) , 
4, 0.18633, 1, 0, 0.463516,-0.0081467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559633,-0.00175335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701854,0.013688) , 
12, 191.231, 1, 0, 0.647318,0.0329028) , 
10, 0.260854, 1, 0, 0.5,1.56986e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485126,0.00331455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348485,-0.0129824) , 
11, 0.778876, 1, 0, 0.399828,-0.0311411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552819,0.00409329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448536,-0.00498933) , 
7, 0.488209, 1, 0, 0.52552,0.00793866) , 
9, 0.17759, 1, 0, 0.5,4.00275e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418301,-0.00643964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584179,0.00706283) , 
12, 335.177, 1, 0, 0.451249,-0.0175356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493116,0.000622134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788066,0.0187608) , 
9, 0.493816, 1, 0, 0.537277,0.0134118) , 
3, 0.38728, 1, 0, 0.5,1.99567e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452711,-0.00293473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64787,0.00862217) , 
8, 0.744825, 1, 0, 0.483495,-0.00541422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606272,0.016734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638743,0.00266888) , 
1, 112.065, 1, 0, 0.624813,0.0409937) , 
13, 0.786379, 1, 0, 0.5,5.98523e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52093,0.000894285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0184988) , 
4, 0.172653, 1, 0, 0.582888,0.0382725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420495,-0.00642168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531844,0.0021731) , 
12, 181.496, 1, 0, 0.48755,-0.00574115) , 
7, 0.135302, 1, 0, 0.5,6.4507e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482871,-0.00398611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573604,0.00712956) , 
4, -0.0585928, 1, 0, 0.548196,0.0184705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435727,-0.00521088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614035,0.00903856) , 
12, 331.736, 1, 0, 0.470189,-0.0114142) , 
11, 0.825454, 1, 0, 0.5,6.48902e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362919,-0.014427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538058,0.00212072) , 
2, 69.0577, 1, 0, 0.438063,-0.0334945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471891,-0.00311389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548555,0.00549599) , 
4, -0.0109534, 1, 0, 0.511364,0.00615277) , 
3, 0.360877, 1, 0, 0.5,6.33503e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3075,-0.0113753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440158,0.000449257) , 
5, 503.01, 1, 0, 0.381557,-0.0208149) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530101,0.000485137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64455,0.00827055) , 
12, 337.756, 1, 0, 0.554761,0.00963056) , 
6, 464.054, 1, 0, 0.5,4.74106e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437398,-0.00343123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636232,0.0077175) , 
8, 0.744825, 1, 0, 0.468721,-0.00787029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542328,-0.002872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624742,0.00906197) , 
3, 0.385817, 1, 0, 0.601632,0.0255853) , 
13, 0.715315, 1, 0, 0.5,2.98849e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345838,-0.0100053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548387,0.0050588) , 
6, 648.724, 1, 0, 0.399828,-0.0269573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615799,0.0107855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512974,0.000208592) , 
7, 0.129981, 1, 0, 0.52552,0.0068726) , 
9, 0.17759, 1, 0, 0.5,3.85105e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351764,-0.0102641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534451,0.00210037) , 
9, 0.277133, 1, 0, 0.444183,-0.0178471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511971,-0.000145785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580528,0.00786109) , 
4, 0.0292343, 1, 0, 0.532871,0.0105145) , 
13, 0.537653, 1, 0, 0.5,2.71414e-06)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416155,-0.00357416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63346,0.00473525) , 
6, 690.863, 1, 0, 0.476543,-0.0059299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540881,-0.00289187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644543,0.0106947) , 
3, 0.388108, 1, 0, 0.611446,0.0281799) , 
13, 0.750847, 1, 0, 0.5,1.21097e-06)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362919,-0.0126098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538058,0.00157855) , 
2, 69.0577, 1, 0, 0.438063,-0.029508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471891,-0.00283393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548555,0.00493665) , 
4, -0.0109534, 1, 0, 0.511364,0.00541637) , 
3, 0.360877, 1, 0, 0.5,2.12035e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0123513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496747,-0.000444296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637346,0.0087732) , 
13, 0.786379, 1, 0, 0.513578,0.00297331) , 
5, 443.688, 1, 0, 0.5,1.11514e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447904,-0.00258471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587891,0.00874977) , 
4, 0.18633, 1, 0, 0.463516,-0.00602737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.00150196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.775244,0.0185271) , 
13, 0.679782, 1, 0, 0.647318,0.0243399) , 
10, 0.260854, 1, 0, 0.5,4.94013e-07)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345756,-0.0131007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555891,0.00272174) , 
9, 0.324526, 1, 0, 0.431204,-0.0299598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491039,-0.000314551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628258,0.00956591) , 
3, 0.409116, 1, 0, 0.511396,0.00496652) , 
13, 0.431056, 1, 0, 0.5,3.17778e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485126,0.00282277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348485,-0.009949) , 
11, 0.778876, 1, 0, 0.399828,-0.0227668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615799,0.0093545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512974,0.000151382) , 
7, 0.129981, 1, 0, 0.52552,0.00580325) , 
9, 0.17759, 1, 0, 0.5,2.44852e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262295,-0.0148906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411765,-0.00113584) , 
6, 338.641, 1, 0, 0.381557,-0.0166408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536545,0.00850875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558069,0.00042595) , 
0, 137.534, 1, 0, 0.554761,0.00769606) , 
6, 464.054, 1, 0, 0.5,1.56837e-06)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396292,-0.00583884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532422,0.00167283) , 
13, 0.546566, 1, 0, 0.486931,-0.00371361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619893,0.00756699) , 
4, 0.198968, 1, 0, 0.5,-5.69595e-07)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565476,0.00630592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455621,-0.00200597) , 
7, 0.135302, 1, 0, 0.470193,-0.00406084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669492,3.89609e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795455,0.0178777) , 
10, 0.348586, 1, 0, 0.728097,0.0310693) , 
9, 0.52975, 1, 0, 0.5,-7.56862e-07)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262295,-0.0135955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479356,-0.000159876) , 
6, 338.643, 1, 0, 0.462715,-0.00496088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669872,0.00934506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718182,-0.00182626) , 
8, 0.679607, 1, 0, 0.686583,0.0248372) , 
6, 823.181, 1, 0, 0.5,2.00608e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499398,-0.00246467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578056,0.00642475) , 
3, 0.387673, 1, 0, 0.548196,0.013546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435727,-0.00414677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614035,0.00787968) , 
12, 331.736, 1, 0, 0.470189,-0.00837675) , 
11, 0.825454, 1, 0, 0.5,1.1873e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338889,-0.00712871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455665,0.00421946) , 
12, 260.626, 1, 0, 0.370794,-0.0176056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509479,0.0106113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549215,0.000308459) , 
8, 0.376478, 1, 0, 0.545262,0.0061694) , 
8, 0.330381, 1, 0, 0.5,1.52425e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345756,-0.0114339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555891,0.00234618) , 
9, 0.324526, 1, 0, 0.431204,-0.0258866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473351,-0.0004035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70559,0.00849699) , 
6, 832.423, 1, 0, 0.511396,0.00428814) , 
13, 0.431056, 1, 0, 0.5,3.87383e-08)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408163,-0.00490913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534602,0.00161632) , 
13, 0.546566, 1, 0, 0.490432,-0.0029107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628141,0.00868908) , 
4, 0.225413, 1, 0, 0.5,4.30313e-07)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565476,0.00579752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455621,-0.00181178) , 
7, 0.135302, 1, 0, 0.470193,-0.0035883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669492,-7.7977e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795455,0.0162493) , 
10, 0.348586, 1, 0, 0.728097,0.0274626) , 
9, 0.52975, 1, 0, 0.5,3.40554e-07)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456284,0.0032359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425287,-0.0108729) , 
4, -0.0266622, 1, 0, 0.438063,-0.0232123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471891,-0.0025497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548555,0.00420173) , 
4, -0.0109534, 1, 0, 0.511364,0.0042618) , 
3, 0.360877, 1, 0, 0.5,2.5529e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466013,-0.00165412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70765,0.0108472) , 
5, 1231.66, 1, 0, 0.483495,-0.00359818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606272,0.0135585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638743,-6.00181e-05) , 
1, 112.065, 1, 0, 0.624813,0.027228) , 
13, 0.786379, 1, 0, 0.5,2.14943e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345838,-0.00765882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548387,0.00467796) , 
6, 648.724, 1, 0, 0.399828,-0.0191242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552819,0.00260295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448536,-0.00322531) , 
7, 0.488209, 1, 0, 0.52552,0.0048761) , 
9, 0.17759, 1, 0, 0.5,3.14191e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377622,-0.00751142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501013,0.00115408) , 
12, 185.055, 1, 0, 0.451249,-0.0104996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493116,8.91359e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788066,0.0140059) , 
9, 0.493816, 1, 0, 0.537277,0.008032) , 
3, 0.38728, 1, 0, 0.5,2.05041e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42204,-0.00416229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530612,0.00168956) , 
12, 181.496, 1, 0, 0.486931,-0.00300643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619893,0.0062108) , 
4, 0.198968, 1, 0, 0.5,3.75769e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345756,-0.010042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555891,0.00187914) , 
9, 0.324526, 1, 0, 0.431204,-0.0228265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491039,-0.000279199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628258,0.00763794) , 
3, 0.409116, 1, 0, 0.511396,0.00378512) , 
13, 0.431056, 1, 0, 0.5,3.36281e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437398,-0.00248504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636232,0.00644384) , 
8, 0.744825, 1, 0, 0.468721,-0.00502201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61483,0.00643666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567639,-0.00362938) , 
11, 0.852887, 1, 0, 0.601632,0.0163296) , 
13, 0.715315, 1, 0, 0.5,2.77665e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450989,-0.00165959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689342,0.00555153) , 
6, 832.423, 1, 0, 0.490432,-0.00241277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628141,0.0072792) , 
4, 0.225413, 1, 0, 0.5,3.23006e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426326,-0.0003606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439344,-0.0119243) , 
12, 264.679, 1, 0, 0.431204,-0.0207701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499779,1.39502e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64467,0.00962784) , 
4, 0.179557, 1, 0, 0.511396,0.00344486) , 
13, 0.431056, 1, 0, 0.5,3.69175e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.00868031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442522,0.00569695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526064,-0.000475613) , 
1, 78.9612, 1, 0, 0.513578,0.00200948) , 
5, 443.688, 1, 0, 0.5,3.73888e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267666,-0.0112918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421131,-0.00010209) , 
8, 0.299501, 1, 0, 0.381557,-0.012318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536545,0.00775625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558069,6.12613e-05) , 
0, 137.534, 1, 0, 0.554761,0.00569875) , 
6, 464.054, 1, 0, 0.5,2.45846e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405749,-0.00451275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51303,0.00134899) , 
4, -0.0125955, 1, 0, 0.468721,-0.00464504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,-0.00292451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646681,0.00632988) , 
12, 151.566, 1, 0, 0.601632,0.015096) , 
13, 0.715315, 1, 0, 0.5,7.33787e-07)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485126,0.00254034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348485,-0.00741517) , 
11, 0.778876, 1, 0, 0.399828,-0.0157685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615799,0.00646529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512974,0.00012557) , 
7, 0.129981, 1, 0, 0.52552,0.00401833) , 
9, 0.17759, 1, 0, 0.5,8.62834e-07)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456284,0.00385625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425287,-0.00964715) , 
4, -0.0266622, 1, 0, 0.438063,-0.0186127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471891,-0.0020987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548555,0.00342911) , 
4, -0.0109534, 1, 0, 0.511364,0.00341533) , 
3, 0.360877, 1, 0, 0.5,3.7716e-07)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466013,-0.00136886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70765,0.00933931) , 
5, 1231.66, 1, 0, 0.483495,-0.00286129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606272,0.0119439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638743,-0.00093538) , 
1, 112.065, 1, 0, 0.624813,0.0216386) , 
13, 0.786379, 1, 0, 0.5,1.64766e-07)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385328,0.000339262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,-0.00946222) , 
1, 86.6681, 1, 0, 0.381557,-0.0111507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536545,0.006993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558069,6.34172e-05) , 
0, 137.534, 1, 0, 0.554761,0.0051571) , 
6, 464.054, 1, 0, 0.5,1.11932e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408163,-0.00368232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534602,0.00125899) , 
13, 0.546566, 1, 0, 0.490432,-0.00200998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628141,0.00609827) , 
4, 0.225413, 1, 0, 0.5,4.41058e-07)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.00764413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442522,0.00527842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526064,-0.000470237) , 
1, 78.9612, 1, 0, 0.513578,0.00174641) , 
5, 443.688, 1, 0, 0.5,3.51488e-07)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345838,-0.00620751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548387,0.004611) , 
6, 648.724, 1, 0, 0.399828,-0.0142194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474142,-0.00140833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563936,0.00254854) , 
3, 0.38728, 1, 0, 0.52552,0.00362208) , 
9, 0.17759, 1, 0, 0.5,-4.05998e-07)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
