import FWCore.ParameterSet.Config as cms

LeptonJetsSkim = cms.EDFilter(
    "LeptonJetsSkim",
    era          = cms.string("NA"),
    isData       = cms.bool(False),
    electrons = cms.InputTag("slimmedElectrons"),
    muons = cms.InputTag("slimmedMuons"),
    photons = cms.InputTag("slimmedPhotons"),
    AK4jets = cms.InputTag("slimmedJetsPuppi"),
    AK8jets = cms.InputTag("selectedPatJetsAK8PFPuppi"),
    AK15jets = cms.InputTag("selectedPatJetsAK15PFPuppi"),
    vertices = cms.InputTag("offlineSlimmedPrimaryVertices"),
    rho = cms.InputTag("fixedGridRhoFastjetAll"),
    met = cms.InputTag("slimmedMETs"),
    met_puppi = cms.InputTag("slimmedMETsPuppi"),
    muonPtMin   = cms.double(15),
    muonEtaMax  = cms.double(2.5),
    electronPtMin   = cms.double(15),
    electronEtaMax  = cms.double(2.5),
    AK4jetPtMin   = cms.double(20),
    AK4jetEtaMax  = cms.double(2.5),
    AK8jetPtMin   = cms.double(60),
    AK8jetEtaMax  = cms.double(2.5),
    minJetsAK4  = cms.int32(1),
    minJetsAK8  = cms.int32(1),
    maxJetsAK4  = cms.int32(7),
    maxJetsAK8  = cms.int32(4),
    minJetsAK15 = cms.int32(1),
    maxJetsAK15 = cms.int32(3),
    photonPtMin = cms.double(15),
    photonEtaMax = cms.double(2.5),
    metPtMin = cms.double(150.)
    )
