// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : flowers1
Date           : Tue Jun 30 15:25:53 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 30 09:43:11 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/flowers1/May2015/CMSSW_7_2_3/src/ttH-LeptonPlusJets/AnalysisCode/macros/TRAINHOUSE
Training events: 410
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
aplanarity                    aplanarity                    aplanarity                    aplanarity                    aplanarity                        'F'    [0.00308504188433,0.403500556946]
third_jet_pt                  third_jet_pt                  third_jet_pt                  third_jet_pt                  third_jet_pt                      'F'    [33.1114234924,245.202728271]
fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                 fourth_jet_pt                     'F'    [31.0782928467,176.121627808]
h1                            h1                            h1                            h1                            h1                                'F'    [-0.177832230926,0.34649592638]
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [0.982467830181,3.45368599892]
sphericity                    sphericity                    sphericity                    sphericity                    sphericity                        'F'    [0.01136678271,0.888938605785]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.869279325008,0.997651696205]
dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags           'F'    [1.7809726387e-06,0.00647709192708]
h2                            h2                            h2                            h2                            h2                                'F'    [-0.0931285098195,0.277725636959]
h3                            h3                            h3                            h3                            h3                                'F'    [-0.00533335655928,0.959015727043]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.815940380096,0.998484194279]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [0.814056634903,0.995792150497]
maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                    'F'    [0.112207077444,1.70176136494]
maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                    'F'    [0.112207077444,1.60389769077]
maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                maxeta_tag_tag                    'F'    [0.103877536952,1.46371901035]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.262612193823,0.95657324791]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "aplanarity", "third_jet_pt", "fourth_jet_pt", "h1", "avg_dr_tagged_jets", "sphericity", "avg_btag_disc_btags", "dev_from_avg_disc_btags", "h2", "h3", "third_highest_btag", "fourth_highest_btag", "maxeta_jet_jet", "maxeta_jet_tag", "maxeta_tag_tag", "pt_all_jets_over_E_all_jets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476378,-0.00472441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246377,-0.0507246) , 
4, 2.39459, 1, 0, 0.427245,-0.0727554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854545,0.0709091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,0.025) , 
7, 0.000471161, 1, 0, 0.770115,0.270115) , 
6, 0.967087, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496183,-0.000290927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0404602) , 
4, 2.15924, 1, 0, 0.392996,-0.0998136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477273,-0.00661257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761468,0.0498424) , 
1, 59.3508, 1, 0, 0.679739,0.167673) , 
6, 0.954861, 1, 0, 0.5,4.49397e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0214824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379447,-0.0214892) , 
8, -0.0401493, 1, 0, 0.427245,-0.0607223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854545,0.0612205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,0.0186715) , 
7, 0.000471161, 1, 0, 0.770115,0.22548) , 
6, 0.967087, 1, 0, 0.5,8.41523e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496183,0.000837472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0351412) , 
4, 2.15924, 1, 0, 0.392996,-0.0833939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477273,-0.00806239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761468,0.0431984) , 
1, 59.3508, 1, 0, 0.679739,0.140171) , 
6, 0.954861, 1, 0, 0.5,3.40601e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0279202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502793,0.00404076) , 
1, 65.3413, 1, 0, 0.427245,-0.050702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854545,0.053894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,0.0136238) , 
7, 0.000471161, 1, 0, 0.770115,0.188429) , 
6, 0.967087, 1, 0, 0.5,4.04866e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22807,-0.0456046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44,-0.00517045) , 
6, 0.910032, 1, 0, 0.392996,-0.0699417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747826,0.0365084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473684,-0.0124558) , 
13, 0.835682, 1, 0, 0.679739,0.117663) , 
6, 0.954861, 1, 0, 0.5,6.69156e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411765,-0.00966051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72028,0.0298109) , 
6, 0.954861, 1, 0, 0.527559,0.0239972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137931,-0.0646669) , 
4, 2.62995, 1, 0, 0.5,7.20776e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.00175581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236111,-0.0391727) , 
4, 2.39459, 1, 0, 0.446023,-0.0318037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.00553349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944444,0.0652035) , 
2, 49.7128, 1, 0, 0.827586,0.193509) , 
11, 0.943868, 1, 0, 0.5,6.97409e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0466299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565982,0.0101856) , 
6, 0.905957, 1, 0, 0.527559,0.0203444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137931,-0.0564474) , 
4, 2.62995, 1, 0, 0.5,9.46853e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474403,-0.000232494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264151,-0.0395405) , 
9, 0.501147, 1, 0, 0.442197,-0.0300447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619048,0.00158163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906977,0.0543154) , 
1, 60.5976, 1, 0, 0.8125,0.16274) , 
6, 0.9732, 1, 0, 0.5,4.84756e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425,-0.00410473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192308,-0.0439998) , 
9, 0.377753, 1, 0, 0.333333,-0.0942915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411765,-0.0159756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65285,0.0208809) , 
1, 59.3508, 1, 0, 0.579137,0.0448902) , 
10, 0.911559, 1, 0, 0.5,8.05032e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0403233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565982,0.00871879) , 
6, 0.905957, 1, 0, 0.527559,0.0174613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137931,-0.0508548) , 
4, 2.62995, 1, 0, 0.5,5.77653e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428135,-0.00867806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68,0.0401542) , 
3, 0.221656, 1, 0, 0.446023,-0.0248945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.00321132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944444,0.0573997) , 
2, 49.7128, 1, 0, 0.827586,0.151184) , 
11, 0.943868, 1, 0, 0.5,1.40793e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.00697361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108108,-0.0650446) , 
9, 0.254537, 1, 0, 0.329114,-0.121404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496622,0.000875122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914286,0.0561718) , 
10, 0.989329, 1, 0, 0.540785,0.0290499) , 
15, 0.493933, 1, 0, 0.5,5.98815e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465517,-0.00354108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26,-0.039353) , 
9, 0.386892, 1, 0, 0.403614,-0.0659629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513967,0.000231865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707692,0.035083) , 
0, 0.123785, 1, 0, 0.565574,0.0449763) , 
1, 63.4102, 1, 0, 0.5,5.94738e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346667,-0.0179387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515306,0.0052786) , 
1, 65.3413, 1, 0, 0.442197,-0.0227366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.000974245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904762,0.04677) , 
15, 0.607099, 1, 0, 0.8125,0.123239) , 
6, 0.9732, 1, 0, 0.5,4.98712e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,0.0185799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18,-0.0480865) , 
9, 0.172877, 1, 0, 0.329114,-0.104836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358974,-0.0124488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640187,0.0154503) , 
10, 0.919973, 1, 0, 0.540785,0.0251149) , 
15, 0.493933, 1, 0, 0.5,7.56232e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.0414483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,0.00413413) , 
15, 0.493933, 1, 0, 0.486979,-0.0125095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.0378902) , 
3, 0.221656, 1, 0, 0.5,4.64738e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521277,0.0085012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319018,-0.0175159) , 
4, 2.04156, 1, 0, 0.392996,-0.0364157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648,0.00609962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821429,0.0477511) , 
3, 0.13109, 1, 0, 0.679739,0.0612223) , 
6, 0.954861, 1, 0, 0.5,1.99695e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0450291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548209,0.00525604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115385,-0.0453877) , 
4, 2.62995, 1, 0, 0.51928,0.0106899) , 
6, 0.893731, 1, 0, 0.5,2.25761e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386207,-0.0171906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0252168) , 
7, 0.00441811, 1, 0, 0.403614,-0.0543639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513967,2.46833e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707692,0.0299742) , 
0, 0.123785, 1, 0, 0.565574,0.0369618) , 
1, 63.4102, 1, 0, 0.5,-1.39692e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428135,-0.00676465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68,0.0322631) , 
3, 0.221656, 1, 0, 0.446023,-0.018369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.000760271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944444,0.0504878) , 
2, 49.7128, 1, 0, 0.827586,0.111408) , 
11, 0.943868, 1, 0, 0.5,-1.02927e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,-0.011068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854545,0.0364624) , 
15, 0.575358, 1, 0, 0.766234,0.0862164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.017335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518519,0.0056234) , 
1, 65.2441, 1, 0, 0.438438,-0.0198963) , 
7, 0.000618477, 1, 0, 0.5,3.21476e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0416662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548209,0.00469717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115385,-0.0415667) , 
4, 2.62995, 1, 0, 0.51928,0.00958757) , 
6, 0.893731, 1, 0, 0.5,4.83157e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.035426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,0.00340185) , 
15, 0.493933, 1, 0, 0.486979,-0.0101932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.0313433) , 
3, 0.221656, 1, 0, 0.5,1.26082e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449438,0.00299559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178571,-0.0368814) , 
9, 0.377753, 1, 0, 0.344828,-0.0516513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661376,0.0155939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394737,-0.0158904) , 
13, 0.835682, 1, 0, 0.584906,0.0282528) , 
10, 0.920251, 1, 0, 0.5,-5.96414e-06)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591549,0.0157326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403636,-0.00862738) , 
8, -0.0401493, 1, 0, 0.442197,-0.0157155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868421,0.0409359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730769,-0.00305179) , 
0, 0.0925322, 1, 0, 0.8125,0.0848159) , 
6, 0.9732, 1, 0, 0.5,-2.28216e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0325173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0252225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.00673822) , 
4, 1.87419, 1, 0, 0.488372,-0.00889204) , 
12, 0.339286, 1, 0, 0.5,7.85982e-07)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386207,-0.0149319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0242453) , 
7, 0.00441811, 1, 0, 0.403614,-0.0442594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613139,0.0169776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504673,-0.00664574) , 
2, 66.6224, 1, 0, 0.565574,0.0301216) , 
1, 63.4102, 1, 0, 0.5,6.36363e-06)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0377753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505464,-0.000346212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73913,0.0344279) , 
3, 0.221656, 1, 0, 0.51928,0.00819329) , 
6, 0.893731, 1, 0, 0.5,3.33982e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477966,0.000956287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280702,-0.0262088) , 
9, 0.495859, 1, 0, 0.446023,-0.0139566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,-0.00104322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944444,0.0454131) , 
2, 49.7128, 1, 0, 0.827586,0.0846767) , 
11, 0.943868, 1, 0, 0.5,-3.61215e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3125,-0.0250436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460784,0.00118381) , 
2, 41.2827, 1, 0, 0.403614,-0.0405663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513967,-0.000718758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707692,0.0251823) , 
0, 0.123785, 1, 0, 0.565574,0.0276357) , 
1, 63.4102, 1, 0, 0.5,2.2207e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0292083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0227107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.00602847) , 
4, 1.87419, 1, 0, 0.488372,-0.00786319) , 
12, 0.339286, 1, 0, 0.5,2.14486e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591549,0.013612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403636,-0.00756585) , 
8, -0.0401493, 1, 0, 0.442197,-0.013658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868421,0.0381379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730769,-0.00323824) , 
0, 0.0925322, 1, 0, 0.8125,0.0739981) , 
6, 0.9732, 1, 0, 0.5,2.49378e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.0304689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,0.00284593) , 
15, 0.493933, 1, 0, 0.486979,-0.00831182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.0262895) , 
3, 0.221656, 1, 0, 0.5,4.11455e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107143,-0.0461545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388889,0.00292595) , 
6, 0.895121, 1, 0, 0.265625,-0.0719148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574074,0.00548431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,-0.043984) , 
4, 2.62995, 1, 0, 0.543353,0.0133302) , 
6, 0.91207, 1, 0, 0.5,2.37041e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346154,-0.025414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429825,-0.000204379) , 
12, 0.63535, 1, 0, 0.403614,-0.0372124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542986,0.00233437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782609,0.0385281) , 
15, 0.857436, 1, 0, 0.565574,0.0252876) , 
1, 63.4102, 1, 0, 0.5,-1.72613e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0281243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535826,0.00186154) , 
15, 0.493933, 1, 0, 0.486702,-0.00906444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647059,0.0217068) , 
3, 0.196688, 1, 0, 0.5,-1.11679e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744186,-0.00202964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794118,0.0369282) , 
7, 0.000260873, 1, 0, 0.766234,0.0616901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0137094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518519,0.00471702) , 
1, 65.2441, 1, 0, 0.438438,-0.0142912) , 
7, 0.000618477, 1, 0, 0.5,-2.15785e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146341,-0.0340348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528053,0.000523795) , 
15, 0.493933, 1, 0, 0.482558,-0.0125255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363636,-0.0142974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704545,0.0296853) , 
10, 0.905908, 1, 0, 0.590909,0.0652067) , 
3, 0.146752, 1, 0, 0.5,-1.25096e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477966,0.000817071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280702,-0.0226486) , 
9, 0.495859, 1, 0, 0.446023,-0.0113582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.914286,0.0387147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,-0.00141154) , 
12, 0.773195, 1, 0, 0.827586,0.068771) , 
11, 0.943868, 1, 0, 0.5,-2.28137e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452991,-0.0039857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810811,0.0276624) , 
10, 0.989792, 1, 0, 0.487113,-0.00662289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0296258) , 
1, 134.107, 1, 0, 0.5,-5.19676e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0256706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0198955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.00528074) , 
4, 1.87419, 1, 0, 0.488372,-0.00669329) , 
12, 0.339286, 1, 0, 0.5,6.87501e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509202,-0.00186785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564103,0.0356705) , 
12, 1.0205, 1, 0, 0.515068,0.00923222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0431533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619048,0.0119299) , 
10, 0.942696, 1, 0, 0.377778,-0.0747805) , 
12, 1.17191, 1, 0, 0.5,1.13133e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791667,0.0482089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535714,-0.00442169) , 
3, -0.0413034, 1, 0, 0.6125,0.0535051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,-0.016787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464912,0.00318561) , 
13, 0.538404, 1, 0, 0.472727,-0.0129827) , 
8, -0.0401493, 1, 0, 0.5,-9.43489e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0245752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384615,-0.0111738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568807,0.0061037) , 
1, 65.2441, 1, 0, 0.488372,-0.00639554) , 
12, 0.339286, 1, 0, 0.5,1.74222e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.0244368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,0.00200797) , 
15, 0.493933, 1, 0, 0.486979,-0.0068539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.0223274) , 
3, 0.221656, 1, 0, 0.5,1.62007e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0298231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.0263356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520548,-0.000370679) , 
10, 0.865296, 1, 0, 0.51928,0.00572033) , 
6, 0.893731, 1, 0, 0.5,-7.08005e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471074,-0.00328402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0249793) , 
3, 0.221656, 1, 0, 0.487113,-0.00594143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0270349) , 
1, 134.107, 1, 0, 0.5,-1.72188e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307692,-0.0417862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453488,-5.17581e-05) , 
8, -0.0224896, 1, 0, 0.434343,-0.0258677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526012,-0.00357144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717949,0.0477596) , 
12, 0.965871, 1, 0, 0.561321,0.0241413) , 
5, 0.387469, 1, 0, 0.5,-9.40131e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399083,-0.000408757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358974,-0.0252605) , 
6, 0.94671, 1, 0, 0.392996,-0.0192893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648,0.00109069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821429,0.0406363) , 
3, 0.13109, 1, 0, 0.679739,0.0323811) , 
6, 0.954861, 1, 0, 0.5,-7.39018e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791667,0.0441789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535714,-0.00322592) , 
3, -0.0413034, 1, 0, 0.6125,0.0508148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272727,-0.0227713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512727,0.00105453) , 
11, 0.831365, 1, 0, 0.472727,-0.0123127) , 
8, -0.0401493, 1, 0, 0.5,4.8804e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509202,-0.001487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564103,0.0309311) , 
12, 1.0205, 1, 0, 0.515068,0.00843008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0407744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619048,0.0113721) , 
10, 0.942696, 1, 0, 0.377778,-0.0683182) , 
12, 1.17191, 1, 0, 0.5,6.48593e-06)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0227779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0187278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.00488465) , 
4, 1.87419, 1, 0, 0.488372,-0.0058945) , 
12, 0.339286, 1, 0, 0.5,-9.69499e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298851,-0.0197506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807692,0.0278434) , 
6, 0.966508, 1, 0, 0.415929,-0.0379453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598985,0.0120865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.0150804) , 
9, 0.386892, 1, 0, 0.531987,0.0144316) , 
5, 0.262102, 1, 0, 0.5,-3.98419e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3125,-0.0224567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460784,0.00302943) , 
2, 41.2827, 1, 0, 0.403614,-0.0291546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613139,0.0139996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504673,-0.00765425) , 
2, 66.6224, 1, 0, 0.565574,0.0198293) , 
1, 63.4102, 1, 0, 0.5,-3.22674e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434524,-0.00380764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.826923,0.0208121) , 
11, 0.943868, 1, 0, 0.487113,-0.00547326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0254193) , 
1, 134.107, 1, 0, 0.5,-5.45315e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.0218602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,0.00182142) , 
15, 0.493933, 1, 0, 0.486979,-0.00567938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.0191323) , 
3, 0.221656, 1, 0, 0.5,4.94958e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386207,-0.0110465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0249867) , 
7, 0.00441811, 1, 0, 0.403614,-0.0263361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613139,0.0128239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504673,-0.0070792) , 
2, 66.6224, 1, 0, 0.565574,0.0179131) , 
1, 63.4102, 1, 0, 0.5,-2.42415e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0205585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47561,-0.0166904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491803,0.00296902) , 
12, 0.535788, 1, 0, 0.488372,-0.00522475) , 
12, 0.339286, 1, 0, 0.5,-3.79122e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506329,-0.00288451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647059,0.0504077) , 
12, 1.00018, 1, 0, 0.52,0.00894166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263158,-0.0310601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0211559) , 
5, 0.379326, 1, 0, 0.383333,-0.0521636) , 
12, 1.09622, 1, 0, 0.5,-5.83144e-07)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452991,-0.00322984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810811,0.0239045) , 
10, 0.989792, 1, 0, 0.487113,-0.00507446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0237451) , 
1, 134.107, 1, 0, 0.5,-1.34489e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385321,-0.0151974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542857,0.00402689) , 
5, 0.289509, 1, 0, 0.498715,-0.0049035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0248668) , 
8, 0.171767, 1, 0, 0.5,-3.36461e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481884,-0.00588148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485294,0.0134412) , 
12, 1.02052, 1, 0, 0.482558,-0.00921486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363636,-0.0119016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704545,0.0237468) , 
10, 0.905908, 1, 0, 0.590909,0.0479918) , 
3, 0.146752, 1, 0, 0.5,-5.97707e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506329,-0.00239357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647059,0.0453533) , 
12, 1.00018, 1, 0, 0.52,0.00883831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263158,-0.0289385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590909,0.0170763) , 
5, 0.379326, 1, 0, 0.383333,-0.0515763) , 
12, 1.09622, 1, 0, 0.5,-2.85032e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522013,-0.00439519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0145052) , 
12, 0.642058, 1, 0, 0.555556,0.0149488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276316,-0.0225692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527273,0.0113986) , 
3, 0.0660352, 1, 0, 0.381679,-0.0318742) , 
13, 0.822536, 1, 0, 0.5,-1.17389e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0202734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644737,0.0152286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474194,-0.00248043) , 
8, -0.0401493, 1, 0, 0.507772,0.0053536) , 
1, 43.211, 1, 0, 0.5,-1.73895e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.019716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0173296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.0044311) , 
4, 1.87419, 1, 0, 0.488372,-0.00499938) , 
12, 0.339286, 1, 0, 0.5,-1.40278e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409574,-0.00783811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56,0.00517033) , 
1, 66.652, 1, 0, 0.487113,-0.00478496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0227362) , 
1, 134.107, 1, 0, 0.5,-8.52803e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258065,-0.026702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460317,0.000312055) , 
1, 45.3567, 1, 0, 0.442197,-0.00857928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868421,0.0342291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730769,-0.0105367) , 
0, 0.0925322, 1, 0, 0.8125,0.0463408) , 
6, 0.9732, 1, 0, 0.5,-6.38285e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0255874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431818,0.0202916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530435,-0.00137402) , 
10, 0.881945, 1, 0, 0.51928,0.00455339) , 
6, 0.893731, 1, 0, 0.5,4.74398e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217391,-0.0221049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427184,-0.00936702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549296,0.00474715) , 
5, 0.262102, 1, 0, 0.516796,0.00473011) , 
10, 0.850711, 1, 0, 0.5,-5.81538e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.0190075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,0.00145239) , 
15, 0.493933, 1, 0, 0.486979,-0.0051866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692308,0.0178735) , 
3, 0.221656, 1, 0, 0.5,-8.64156e-06)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46875,-0.0288711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501401,0.00143206) , 
4, 1.72993, 1, 0, 0.498715,-0.0045405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.023358) , 
8, 0.171767, 1, 0, 0.5,-1.28291e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0182438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0171396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.00427284) , 
4, 1.87419, 1, 0, 0.488372,-0.00455898) , 
12, 0.339286, 1, 0, 0.5,-8.85509e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571429,-0.00586847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708333,0.0392666) , 
4, 2.25567, 1, 0, 0.6125,0.0375738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,-0.0157463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464912,0.00399616) , 
13, 0.538404, 1, 0, 0.472727,-0.00911388) , 
8, -0.0401493, 1, 0, 0.5,-4.09827e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487179,-0.000553453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911111,0.034832) , 
11, 0.9439, 1, 0, 0.555556,0.0131756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357143,-0.0155002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,0.0216876) , 
8, 0.0820669, 1, 0, 0.381679,-0.0280617) , 
13, 0.822536, 1, 0, 0.5,-2.0798e-07)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294118,-0.0156565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523952,0.00406977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47619,-0.0181763) , 
0, 0.193759, 1, 0, 0.518617,0.00563526) , 
11, 0.822711, 1, 0, 0.5,1.37716e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571429,-0.00463819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708333,0.0368358) , 
4, 2.25567, 1, 0, 0.6125,0.0376902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,-0.0147158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464912,0.00350994) , 
13, 0.538404, 1, 0, 0.472727,-0.00912239) , 
8, -0.0401493, 1, 0, 0.5,1.17767e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509202,-0.00117887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564103,0.0255327) , 
12, 1.0205, 1, 0, 0.515068,0.0069358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0370547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619048,0.0110235) , 
10, 0.942696, 1, 0, 0.377778,-0.0561278) , 
12, 1.17191, 1, 0, 0.5,1.41849e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462687,-0.0123376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584906,0.00780622) , 
5, 0.262102, 1, 0, 0.555556,0.0134275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276316,-0.020629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527273,0.0103403) , 
3, 0.0660352, 1, 0, 0.381679,-0.0285931) , 
13, 0.822536, 1, 0, 0.5,1.39562e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491573,0.000803633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4375,-0.0238783) , 
1, 104.984, 1, 0, 0.487113,-0.00452758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0221446) , 
1, 134.107, 1, 0, 0.5,-4.79406e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386207,-0.00965856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0217184) , 
7, 0.00441811, 1, 0, 0.403614,-0.0224525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542986,0.000366383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782609,0.0350524) , 
15, 0.857436, 1, 0, 0.565574,0.0152711) , 
1, 63.4102, 1, 0, 0.5,-2.33698e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46875,-0.0269437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501401,0.00135677) , 
4, 1.72993, 1, 0, 0.498715,-0.00421109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0218068) , 
8, 0.171767, 1, 0, 0.5,1.71292e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294118,-0.0152215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523952,0.00374857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47619,-0.0162516) , 
0, 0.193759, 1, 0, 0.518617,0.00538735) , 
11, 0.822711, 1, 0, 0.5,3.55513e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522727,-0.00930736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722222,0.0301749) , 
8, -0.0588859, 1, 0, 0.6125,0.037383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,-0.0139912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464912,0.00318987) , 
13, 0.538404, 1, 0, 0.472727,-0.00905963) , 
8, -0.0401493, 1, 0, 0.5,2.33754e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0183947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0176414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.0043717) , 
4, 1.87419, 1, 0, 0.488372,-0.00453753) , 
12, 0.339286, 1, 0, 0.5,8.60733e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522013,-0.00408794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.012672) , 
12, 0.642058, 1, 0, 0.555556,0.0121746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415094,0.000622433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24,-0.0352618) , 
1, 93.6996, 1, 0, 0.381679,-0.0258927) , 
13, 0.822536, 1, 0, 0.5,1.16451e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324675,-0.0171582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47191,0.00488169) , 
2, 42.7404, 1, 0, 0.403614,-0.0217266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542986,0.00051269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782609,0.0330054) , 
15, 0.857436, 1, 0, 0.565574,0.0147898) , 
1, 63.4102, 1, 0, 0.5,5.09084e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571429,-0.00427683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708333,0.0343014) , 
4, 2.25567, 1, 0, 0.6125,0.0348618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460123,0.00621186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48503,-0.00957838) , 
15, 0.626116, 1, 0, 0.472727,-0.00844293) , 
8, -0.0401493, 1, 0, 0.5,6.76883e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506329,-0.00220649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647059,0.040524) , 
12, 1.00018, 1, 0, 0.52,0.00755963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366667,-0.0320498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,0.0114486) , 
4, 2.29326, 1, 0, 0.383333,-0.0440399) , 
12, 1.09622, 1, 0, 0.5,8.47742e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48048,-0.00061076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.885714,0.031363) , 
10, 0.989792, 1, 0, 0.519022,0.00605153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47619,0.00693841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190476,-0.037113) , 
9, 0.246546, 1, 0, 0.333333,-0.0529742) , 
14, 1.07519, 1, 0, 0.5,4.99954e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586207,0.0157591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18,-0.0280823) , 
9, 0.172877, 1, 0, 0.329114,-0.0357565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496622,-0.000407146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914286,0.0349662) , 
10, 0.989329, 1, 0, 0.540785,0.00854689) , 
15, 0.493933, 1, 0, 0.5,1.03803e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444444,0.0186901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466667,-0.0292358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507082,0.00131422) , 
4, 1.72993, 1, 0, 0.503916,-0.00458858) , 
5, 0.136734, 1, 0, 0.5,1.37524e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,0.0174257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678571,0.0169967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456193,-0.00418274) , 
4, 1.87419, 1, 0, 0.488372,-0.00425145) , 
12, 0.339286, 1, 0, 0.5,1.37064e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409574,-0.0071104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56,0.00482418) , 
1, 66.652, 1, 0, 0.487113,-0.00392966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.019989) , 
1, 134.107, 1, 0, 0.5,1.59217e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294118,-0.0145313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409091,0.019598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533133,-0.00115459) , 
10, 0.882497, 1, 0, 0.518617,0.00504001) , 
11, 0.822711, 1, 0, 0.5,1.51871e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352113,-0.0220528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0201947) , 
1, 79.0874, 1, 0, 0.415929,-0.0272646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598985,0.00998749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.0134917) , 
9, 0.386892, 1, 0, 0.531987,0.0103842) , 
5, 0.262102, 1, 0, 0.5,7.81836e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47482,-0.00126292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772727,0.0479224) , 
2, 62.1905, 1, 0, 0.496667,0.010622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.03356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6875,0.0132015) , 
11, 0.864615, 1, 0, 0.509091,-0.0289591) , 
2, 65.6124, 1, 0, 0.5,2.67506e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46875,-0.0246335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501401,0.00120767) , 
4, 1.72993, 1, 0, 0.498715,-0.00402277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,0.0211033) , 
8, 0.171767, 1, 0, 0.5,1.93292e-06)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
